// SanoVids — pure rules of the desktop auto-updater (electron/updater.cjs), of the code-signature check
// (electron/signature.cjs) and of where the app runs from (main.cjs: 'app:placement', the portable window's taskbar
// identity). Unit-tested by src/lib/__tests__/updaterRules.test.ts and signature.test.ts.
//
// No require at all: not 'electron', not any npm package. In the packaged app.asar, electron-updater's own helpers
// (semver…) are nested under node_modules/electron-updater and cannot be resolved from electron/, so versions are
// compared here by hand. Everything is plain data in, plain data out (paths go through an injected node:path flavour).
'use strict'

/** The public download page (opened by main only; the renderer never sends a URL). */
const RELEASES_URL = 'https://github.com/JameSteven404/sanovids-releases/releases/latest'
/**
 * For tests and logs only: the real feed is resources/app-update.yml, generated by electron-builder from
 * package.json build.publish. The app never calls setFeedURL.
 */
const FEED = Object.freeze({ provider: 'github', owner: 'JameSteven404', repo: 'sanovids-releases' })

const NOTES_MAX = 8000 // = src/lib/updateTypes.ts UPDATE_NOTES_MAX
const VERSION_MAX = 64
const RELEASE_DATE_MAX = 40
const LOG_LINE_MAX = 4000
const PROFILE_DIR_MAX = 240
const INSTALL_NOTICE_MS = 7 * 24 * 60 * 60_000
/**
 * An install on quit runs for ~15 s after the window closed. A launch inside this window is still the old version while
 * the installer works: it says nothing and keeps the attempt for the next launch (never a false "install failed").
 */
const INSTALL_GRACE_MS = 2 * 60_000
const CHECK_EVERY_MS = 4 * 60 * 60_000
const CHECK_RETRY_MS = 30 * 60_000

const VERSION_RE = /^\d+\.\d+\.\d+([-+.][0-9A-Za-z.-]+)?$/

/**
 * 'signature': the downloaded file is NOT the author's signed update (another signer, no signature, modified, or a
 * genuine but other / older build) — refused. 'signature-unverified': the check itself could not decide (PowerShell
 * blocked, restricted or too slow, unexpected chain, no pin) — nothing installed, "Thử lại" checks again.
 * Same list as src/lib/updateTypes.ts UpdateErrorCode.
 */
const ERROR_CODES = ['offline', 'no-release', 'rate-limited', 'checksum', 'signature', 'signature-unverified', 'disk', 'install-failed', 'failed']

/** Fixed Vietnamese texts: raw error text, stacks, XML or headers never reach the renderer. */
const ERROR_TEXT = {
  offline: 'Không kết nối được máy chủ cập nhật.',
  'no-release': 'Chưa tìm thấy bản cập nhật nào trên trang tải về.',
  'rate-limited': 'Máy chủ cập nhật đang bận.',
  checksum: 'File cập nhật tải về bị lỗi (sai mã kiểm tra) nên đã bị bỏ.',
  // Never "download it from the release page": that page may be the very place that served the refused file.
  signature:
    'Bản cập nhật này không mang chữ ký số đúng của tác giả hoặc không đúng phiên bản được báo (có thể là file giả mạo) nên SanoVids đã xoá nó, không cài gì. Đừng tự tải bản này về cài. Chỉ cài bộ cài có dấu vân tay chứng chỉ trùng với Cài đặt → Giới thiệu, hoặc hỏi tác giả.',
  'signature-unverified':
    'Chưa kiểm tra được chữ ký số của bản cập nhật (máy đang chặn việc kiểm tra hoặc kiểm tra quá lâu) nên SanoVids chưa cài bản này. Bấm “Thử lại” để kiểm tra lại.',
  disk: 'Ổ đĩa không đủ chỗ để tải bản cập nhật.',
  'install-failed': 'Không khởi động được trình cài bản cập nhật.',
}
const FAILED_TEXT = { check: 'Không kiểm tra được bản cập nhật.', download: 'Tải bản cập nhật bị lỗi.' }

const NO_RELEASE_CODES = new Set([
  'HTTP_ERROR_404',
  'ERR_XML_MISSED_ELEMENT',
  'ERR_UPDATER_NO_PUBLISHED_VERSIONS',
  'ERR_UPDATER_LATEST_VERSION_NOT_FOUND',
  'ERR_UPDATER_CHANNEL_FILE_NOT_FOUND',
])
const OFFLINE_RE = /net::ERR_|ENOTFOUND|ECONNRESET|ECONNREFUSED|ETIMEDOUT|EAI_AGAIN/

// ---- versions ----

/** "1.2.3", "0.5.0-beta.1" (at most 64 chars). */
function isVersion(v) {
  return typeof v === 'string' && v.length <= VERSION_MAX && VERSION_RE.test(v)
}

function parseVersion(v) {
  if (!isVersion(v)) return null
  const m = /^(\d+)\.(\d+)\.(\d+)(.*)$/.exec(v)
  // Build metadata ("+abc") never changes the order; anything else after x.y.z is a pre-release.
  const rest = m[4].replace(/\+.*$/, '')
  return { nums: [Number(m[1]), Number(m[2]), Number(m[3])], pre: rest ? rest.replace(/^[-.]/, '').split('.') : [] }
}

function compareIds(a, b) {
  const an = /^\d+$/.test(a)
  const bn = /^\d+$/.test(b)
  if (an && bn) return Math.sign(Number(a) - Number(b))
  if (an !== bn) return an ? -1 : 1 // numeric identifiers sort below alphanumeric ones (semver)
  return a < b ? -1 : a > b ? 1 : 0
}

/**
 * -1 | 0 | 1 on numeric x.y.z; a pre-release ("0.5.0-beta") sorts below its plain version ("0.5.0").
 * Something that is not a version sorts below every version (two of them are equal).
 */
function compareVersions(a, b) {
  const pa = parseVersion(a)
  const pb = parseVersion(b)
  if (!pa || !pb) return pa ? 1 : pb ? -1 : 0
  for (let i = 0; i < 3; i++) if (pa.nums[i] !== pb.nums[i]) return pa.nums[i] < pb.nums[i] ? -1 : 1
  if (!pa.pre.length || !pb.pre.length) return pa.pre.length === pb.pre.length ? 0 : pa.pre.length ? -1 : 1
  for (let i = 0; i < Math.max(pa.pre.length, pb.pre.length); i++) {
    if (i >= pa.pre.length) return -1
    if (i >= pb.pre.length) return 1
    const c = compareIds(pa.pre[i], pb.pre[i])
    if (c) return c
  }
  return 0
}

// ---- data folder (test-only isolation) ----

function profileKey(p, pathMod) {
  let r = pathMod.resolve(p)
  const root = pathMod.parse(r).root
  if (r.length > root.length) r = r.replace(/[\\/]+$/, '')
  return pathMod.sep === '\\' ? r.toLowerCase() : r
}

/**
 * `p` with every existing part resolved by the file system (junctions, symlinks, 8.3 short names → long names); the part
 * that does not exist yet is appended as written. fsMod = { existsSync, realpathSync } (main passes node:fs with
 * realpathSync.native). Anything failing → the lexical path (the lexical checks still apply).
 */
function canonicalPath(p, pathMod, fsMod) {
  let cur = pathMod.resolve(p)
  const tail = []
  for (let i = 0; i < 128; i++) {
    let real = null
    try {
      if (fsMod.existsSync(cur)) real = fsMod.realpathSync(cur)
    } catch {
      real = null
    }
    if (typeof real === 'string' && real) return tail.length ? pathMod.join(real, ...tail.reverse()) : real
    const parent = pathMod.dirname(cur)
    if (parent === cur) break
    tail.push(pathMod.basename(cur))
    cur = parent
  }
  return pathMod.resolve(p)
}

/** '' when `key` is neither the real folder, inside it, nor one of its parents; else why not. */
function overlapProblem(key, realKey, sep) {
  if (key === realKey) return 'it is the real SanoVids data folder'
  if (key.startsWith(realKey + sep)) return 'it is inside the real SanoVids data folder'
  if (realKey.startsWith(key.endsWith(sep) ? key : key + sep)) return 'it contains the real SanoVids data folder'
  return ''
}

/** Why `candidate` may not be used as the data folder ('' when it may). */
function profileDirProblem(candidate, real, pathMod, fsMod) {
  if (candidate.length > PROFILE_DIR_MAX) return `longer than ${PROFILE_DIR_MAX} characters`
  if (candidate.includes('\u0000')) return 'contains a NUL character'
  if (!pathMod.isAbsolute(candidate)) return 'not an absolute path'
  const win = pathMod.sep === '\\'
  // Windows aliases of a folder that a string comparison cannot see through: refused outright.
  if (win && /^[\\/]{2}/.test(candidate)) return 'a UNC or device path (\\\\server\\…, \\\\?\\…, \\\\.\\…)'
  if (win && candidate.indexOf(':', 2) !== -1) return 'contains ":" after the drive letter (alternate data stream)'
  const resolved = pathMod.resolve(candidate)
  const root = pathMod.parse(resolved).root
  if (resolved.replace(/[\\/]+$/, '') === root.replace(/[\\/]+$/, '')) return 'a filesystem root'
  if (win) {
    const parts = resolved.slice(root.length).split(/[\\/]+/).filter(Boolean)
    // Win32 drops trailing dots / spaces ("SanoVids." is SanoVids); "~" is how 8.3 short names look ("SANOVI~1").
    if (parts.some((s) => /[. ]$/.test(s))) return 'a folder name ends with a dot or a space'
    if (parts.some((s) => s.includes('~'))) return 'contains "~" (8.3 short names are refused)'
  }
  const lexical = overlapProblem(profileKey(resolved, pathMod), profileKey(real, pathMod), pathMod.sep)
  if (lexical) return lexical
  if (fsMod && typeof fsMod.existsSync === 'function' && typeof fsMod.realpathSync === 'function') {
    const canonical = overlapProblem(
      profileKey(canonicalPath(resolved, pathMod, fsMod), pathMod),
      profileKey(canonicalPath(real, pathMod, fsMod), pathMod),
      pathMod.sep,
    )
    if (canonical) return `${canonical} (after resolving links)`
  }
  return ''
}

/**
 * The userData folder. Real users: %APPDATA%\SanoVids (or <appData>\<appName> for another product name).
 * Agent / E2E tests only: SANOVIDS_PROFILE_DIR (env), else `sanovidsTestProfileDir` baked into the packaged
 * package.json by test builds. Such a folder must be absolute, not a root, never the real folder, inside it or one of
 * its parents — also through Windows aliases (UNC / \\?\ paths, trailing dots or spaces, 8.3 names, streams) and, with
 * `fsMod` ({ existsSync, realpathSync }), through junctions / symlinks: otherwise { ok: false } and the app refuses to
 * start (fail closed).
 * → { ok: true, dir, source: 'env' | 'baked' | 'default' } | { ok: false, error }
 */
function resolveProfileDir({ env, baked, appData, appName, pathMod, fsMod }) {
  const real = pathMod.join(appData, 'SanoVids')
  const fromEnv = typeof env === 'string' && env !== ''
  const candidate = fromEnv ? env : typeof baked === 'string' && baked !== '' ? baked : null
  if (candidate === null) {
    if (appName === 'SanoVids') return { ok: true, dir: real, source: 'default' }
    let leaf = String(appName || '').replace(/[^A-Za-z0-9._-]/g, '_')
    if (/^\.*$/.test(leaf)) leaf = 'SanoVids-other' // never '', '.' or '..'
    return { ok: true, dir: pathMod.join(appData, leaf), source: 'default' }
  }
  const problem = profileDirProblem(candidate, real, pathMod, fsMod)
  if (problem) return { ok: false, error: `SANOVIDS_PROFILE_DIR / sanovidsTestProfileDir is invalid: ${problem}` }
  return { ok: true, dir: pathMod.resolve(candidate), source: fromEnv ? 'env' : 'baked' }
}

/** Windows taskbar / notification identity: the real app keeps com.sanovids.app, test builds get their own. */
function appUserModelId(appName) {
  if (appName === 'SanoVids') return 'com.sanovids.app'
  return 'com.sanovids.test.' + String(appName || '').toLowerCase().replace(/[^a-z0-9]/g, '')
}

/**
 * 'dev'       not packaged (`electron .`): never checks;
 * 'portable'  the portable .exe (PORTABLE_EXECUTABLE_FILE), win-unpacked or a copied exe: check only;
 * 'installer' an NSIS install (its uninstaller sits next to the exe): check, download, install.
 */
function detectKind({ platform, isPackaged, portableFile, execPath, appName, exists, pathMod }) {
  if (!isPackaged) return 'dev'
  if (typeof portableFile === 'string' && portableFile !== '') return 'portable'
  if (platform === 'win32' && typeof execPath === 'string' && execPath !== '') {
    let found = false
    try {
      found = !!exists(pathMod.join(pathMod.dirname(execPath), `Uninstall ${appName}.exe`))
    } catch {
      found = false
    }
    if (found) return 'installer'
  }
  return 'portable'
}

/** Is `child` strictly inside `parent` (both already absolute, resolved by the caller)? */
function isInsideDir(parent, child, pathMod) {
  const rel = pathMod.relative(parent, child)
  if (!rel || pathMod.isAbsolute(rel)) return false
  return rel.split(/[\\/]+/)[0] !== '..'
}

/**
 * Where this SanoVids runs from (main.cjs IPC 'app:placement' → Cài đặt → Ứng dụng / Giới thiệu hints). Only a kind
 * ever leaves the main process, never a path.
 *   'installer' | 'portable' | 'dev'  exactly detectKind (the kind of the updater's UpdateState);
 *   'temp-copy' a portable-kind exe WITHOUT PORTABLE_EXECUTABLE_FILE running from inside the Windows temp folder — a
 *               leftover copy of a Setup / Portable extraction ("…\Temp\ns*.tmp\7z-out\") that Windows may delete at any
 *               time. The real Portable .exe also runs from %TEMP% but sets PORTABLE_EXECUTABLE_FILE: 'portable'.
 * The containment test compares the REAL paths of both (realpath = fs.realpathSync.native: TEMP is often an 8.3 short
 * path such as C:\Users\MINHM~1\…); any failure → not 'temp-copy'. Never throws.
 */
function placement({ platform, isPackaged, portableFile, execPath, tmpDir, appName, exists, realpath, pathMod }) {
  let kind
  try {
    kind = detectKind({ platform, isPackaged, portableFile, execPath, appName, exists, pathMod })
  } catch {
    return isPackaged ? 'portable' : 'dev'
  }
  if (kind !== 'portable') return kind
  if (typeof portableFile === 'string' && portableFile !== '') return 'portable'
  try {
    if (typeof realpath !== 'function') return 'portable'
    for (const p of [execPath, tmpDir]) {
      if (typeof p !== 'string' || p === '' || p.length > 1024 || p.includes('\u0000') || !pathMod.isAbsolute(p)) return 'portable'
    }
    const realExec = realpath(execPath)
    const realTmp = realpath(tmpDir)
    if (typeof realExec !== 'string' || typeof realTmp !== 'string' || !realExec || !realTmp) return 'portable'
    return isInsideDir(pathMod.resolve(realTmp), pathMod.resolve(realExec), pathMod) ? 'temp-copy' : 'portable'
  } catch {
    return 'portable'
  }
}

/**
 * Taskbar identity of the PORTABLE build's window (BrowserWindow.setAppDetails): the portable stub extracts the app to
 * %TEMP%\ns*.tmp\app and deletes it on exit, so a window pinned as is would point at that temp copy. With these details
 * the pin relaunches the portable .exe itself, with its own icon. Only for a packaged win32 run whose
 * PORTABLE_EXECUTABLE_FILE is an absolute path to an existing .exe without '"', CR, LF or NUL (it is quoted into the
 * relaunch command); anything else → null (nothing set). Never throws.
 * → { appId, appIconPath, appIconIndex: 0, relaunchCommand: '"<file>"', relaunchDisplayName } | null
 */
function portableRelaunch({ platform, isPackaged, portableFile, appName, exists, pathMod }) {
  if (platform !== 'win32' || !isPackaged) return null
  if (typeof portableFile !== 'string' || portableFile === '' || portableFile.length > 1024) return null
  if (/["\r\n\u0000]/.test(portableFile)) return null
  try {
    if (!pathMod.isAbsolute(portableFile) || pathMod.extname(portableFile).toLowerCase() !== '.exe') return null
    if (!exists(portableFile)) return null
  } catch {
    return null
  }
  const name = typeof appName === 'string' && appName.trim() ? appName.trim().slice(0, 100) : 'SanoVids'
  return {
    appId: appUserModelId(appName),
    appIconPath: portableFile,
    appIconIndex: 0,
    relaunchCommand: `"${portableFile}"`,
    relaunchDisplayName: name,
  }
}

// ---- errors ----

/** Error of electron-updater → { code, message } with a fixed Vietnamese message. phase: 'check' | 'download' | 'install'. */
function mapUpdaterError(err, phase) {
  const message = (code) => ERROR_TEXT[code] || FAILED_TEXT[phase] || FAILED_TEXT.check
  // An install that did not start is always 'install-failed' (the state goes back to 'ready' with it).
  if (phase === 'install') return { code: 'install-failed', message: message('install-failed') }
  const code = err && typeof err.code === 'string' ? err.code : ''
  const text = err && typeof err.message === 'string' ? err.message : typeof err === 'string' ? err : ''
  // A rejected signature (our pinned verifier, through electron-updater) decides before anything its message may
  // contain: the file was refused, whatever else went wrong around it. Our verifier's reason ("sanovids-signature:<r>")
  // tells a refused file from a check that could not decide.
  if (code === 'ERR_UPDATER_INVALID_SIGNATURE') {
    const sig = signatureErrorCode(signatureReasonOf(text))
    return { code: sig, message: message(sig) }
  }
  const all = `${code} ${text}`
  // GitHubProvider wraps ANY failure of releases/latest (429, 403, 5xx…) in ERR_UPDATER_LATEST_VERSION_NOT_FOUND, with
  // the HttpError stack in the message ("…: HttpError: 429 Too Many Requests"): the real status decides first.
  const wrapped = /HttpError: (\d{3})\b/.exec(text)
  const status = wrapped ? Number(wrapped[1]) : 0
  let out = 'failed'
  // Offline first: electron-updater wraps some network failures in "not found" codes (e.g. the latest.yml fetch).
  if (OFFLINE_RE.test(all)) out = 'offline'
  else if (status === 429 || status === 403) out = 'rate-limited'
  else if (status >= 500 && status <= 599) out = 'failed'
  else if (NO_RELEASE_CODES.has(code) || /No published versions/i.test(text)) out = 'no-release'
  else if (code === 'HTTP_ERROR_429' || code === 'HTTP_ERROR_403') out = 'rate-limited'
  else if (code === 'ERR_CHECKSUM_MISMATCH' || /sha512 checksum mismatch/i.test(text)) out = 'checksum'
  else if (code === 'ENOSPC' || /\bENOSPC\b/.test(text)) out = 'disk'
  return { code: out, message: message(out) }
}

// ---- release notes ----

/**
 * Real HTML element names (what GitHub renders release notes with, plus the dangerous ones). Only these make notes
 * "HTML" and only these are stripped: "<phiên bản>", "<version>" or "a < 5 và > 3" are text and stay text.
 */
const HTML_TAGS =
  'a|abbr|article|aside|b|blockquote|body|br|button|caption|center|code|col|colgroup|dd|del|details|dfn|div|dl|dt|em|embed|' +
  'figcaption|figure|font|footer|form|g-emoji|h[1-6]|head|header|hr|html|i|iframe|img|input|ins|kbd|li|link|main|mark|meta|' +
  'nav|object|ol|p|picture|pre|q|s|samp|script|section|small|source|span|strike|strong|style|sub|summary|sup|svg|table|' +
  'tbody|td|template|tfoot|th|thead|time|title|tr|tt|u|ul|var|video'
const HTML_TAG_RE = new RegExp(`</?(?:${HTML_TAGS})(?=[\\s/>])[^>]*>`, 'i')
const HTML_TAG_RE_G = new RegExp(HTML_TAG_RE.source, 'gi')
/** Whitespace between two real tags (meaningless in HTML). */
const BETWEEN_TAGS_RE = new RegExp(`(${HTML_TAG_RE.source})\\s+(?=${HTML_TAG_RE.source})`, 'gi')
const ENTITY_RE = /&(#x[0-9a-f]{1,6}|#\d{1,7}|amp|lt|gt|quot|apos|nbsp);/gi
const NAMED_ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' }

function decodeEntities(s) {
  // One pass: "&amp;lt;" becomes "&lt;" (text), never "<".
  return s.replace(ENTITY_RE, (whole, body) => {
    const lower = body.toLowerCase()
    if (lower[0] !== '#') return NAMED_ENTITIES[lower]
    const cp = lower[1] === 'x' ? parseInt(lower.slice(2), 16) : parseInt(lower.slice(1), 10)
    if (!Number.isFinite(cp) || cp <= 0 || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return ''
    return String.fromCodePoint(cp)
  })
}

/** GitHub-rendered HTML → markdown-ish plain text (entities decoded last, so they always stay text). */
function htmlToText(s) {
  return decodeEntities(
    s
      .replace(/<(script|style)\b[\s\S]*?<\/\1\s*>/gi, '')
      // Whitespace between two tags means nothing in HTML (only the tags below break lines there). Newlines inside text
      // are kept: markdown notes with one inline tag ("- <b>x</b>") also land here and must keep their lines.
      .replace(BETWEEN_TAGS_RE, '$1')
      .replace(/[ \t\f\v]+/g, ' ')
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<\/(p|div|li|ul|ol|h[1-6])\s*>/gi, '\n')
      .replace(/<li\b[^>]*>/gi, '- ')
      .replace(/<h[1-6]\b[^>]*>/gi, '## ')
      .replace(HTML_TAG_RE_G, '')
      .replace(/^ +| +$/gm, ''),
  )
}

function noteText(s) {
  const t = s.replace(/\r\n?/g, '\n')
  return HTML_TAG_RE.test(t) ? htmlToText(t) : t
}

/**
 * releaseNotes of latest.yml / the GitHub feed → PLAIN TEXT (markdown-ish, never HTML), at most 8000 chars.
 * Accepts a string (markdown or HTML) or electron-updater's [{ version, note }] list.
 */
function notesToText(releaseNotes) {
  let text = ''
  if (typeof releaseNotes === 'string') text = noteText(releaseNotes)
  else if (Array.isArray(releaseNotes)) {
    text = releaseNotes
      .filter((r) => r && typeof r === 'object')
      .map((r) => {
        const version = typeof r.version === 'string' ? r.version.slice(0, VERSION_MAX) : ''
        const note = typeof r.note === 'string' ? noteText(r.note) : ''
        return [version, note].filter(Boolean).join('\n')
      })
      .filter(Boolean)
      .join('\n\n')
  }
  text = text
    .replace(/\r/g, '\n')
    .replace(/[\u0000-\u0008\u000b-\u001f\u007f-\u009f]/g, '')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
  if (text.length > NOTES_MAX) {
    let head = text.slice(0, NOTES_MAX - 1)
    const nl = head.lastIndexOf('\n')
    if (nl > 0) head = head.slice(0, nl)
    else if (/[\ud800-\udbff]$/.test(head)) head = head.slice(0, -1)
    text = head.trimEnd() + '…'
  }
  return text
}

/** UpdateInfo of electron-updater → { version, releaseDate?, notes, size? } | null (invalid version: ignore the event). */
function normalizeInfo(info) {
  if (!info || typeof info !== 'object' || !isVersion(info.version)) return null
  const out = { version: info.version, notes: notesToText(info.releaseNotes) }
  if (typeof info.releaseDate === 'string' && info.releaseDate) out.releaseDate = info.releaseDate.slice(0, RELEASE_DATE_MAX)
  const first = Array.isArray(info.files) ? info.files[0] : null
  const size = first && typeof first === 'object' ? first.size : undefined
  if (typeof size === 'number' && Number.isFinite(size) && size >= 0) out.size = size
  return out
}

// ---- state machine (same shapes as src/lib/updateTypes.ts) ----

const PROGRESS_KEYS = ['percent', 'transferred', 'total', 'bytesPerSecond']
const RELEASE_KEYS = ['version', 'releaseDate', 'notes', 'size']

function without(state, keys) {
  const out = { ...state }
  for (const k of keys) delete out[k]
  return out
}

function initialState({ kind, current, autoDownload, notice }) {
  const state = {
    kind,
    current: typeof current === 'string' ? current.slice(0, VERSION_MAX) : '',
    status: kind === 'dev' ? 'unsupported' : 'idle',
    autoDownload: autoDownload !== false,
  }
  if (notice) state.notice = notice
  return state
}

function finiteNonNeg(v) {
  return typeof v === 'number' && Number.isFinite(v) && v >= 0 ? v : undefined
}

function progressFields(p) {
  const o = p && typeof p === 'object' ? p : {}
  const out = {}
  const percent = finiteNonNeg(o.percent)
  if (percent !== undefined) out.percent = Math.min(100, percent)
  for (const k of ['transferred', 'total', 'bytesPerSecond']) {
    const v = finiteNonNeg(o[k])
    if (v !== undefined) out[k] = v
  }
  return out
}

function releaseFields(info) {
  const out = { version: info.version }
  if (typeof info.releaseDate === 'string' && info.releaseDate) out.releaseDate = info.releaseDate.slice(0, RELEASE_DATE_MAX)
  if (typeof info.notes === 'string') out.notes = info.notes.slice(0, NOTES_MAX)
  const size = finiteNonNeg(info.size)
  if (size !== undefined) out.size = size
  return out
}

function validError(error, fallbackCode) {
  if (error && ERROR_CODES.includes(error.code) && typeof error.message === 'string') {
    return { code: error.code, message: error.message.slice(0, 300) }
  }
  return { code: fallbackCode, message: ERROR_TEXT[fallbackCode] || FAILED_TEXT.check }
}

/**
 * The updater state machine (docs: SPEC A.4). Pure: returns the same object when nothing changes.
 * `event.info` is the output of normalizeInfo; `event.error` the output of mapUpdaterError.
 */
function reduceUpdateState(state, event, now) {
  if (!event || typeof event !== 'object') return state
  const busy = state.status === 'downloading' || state.status === 'ready'
  switch (event.type) {
    case 'checking':
      // A known update stays announced while it is checked again: no pill flicker, and a failed re-check (electron-updater
      // always emits checking-for-update first) keeps it instead of turning it into an error.
      if (busy || state.status === 'available') return state
      return { ...without(state, ['error']), status: 'checking' }
    case 'not-available':
      if (busy) return { ...state, lastCheck: now }
      return { ...without(state, [...RELEASE_KEYS, ...PROGRESS_KEYS, 'error']), status: 'none', lastCheck: now }
    case 'available': {
      const info = event.info
      if (!info || !isVersion(info.version)) return state
      if (busy && info.version === state.version) return { ...state, lastCheck: now }
      return { ...without(state, [...RELEASE_KEYS, ...PROGRESS_KEYS, 'error']), ...releaseFields(info), status: 'available', lastCheck: now }
    }
    case 'progress':
      return { ...without(state, [...PROGRESS_KEYS, 'error']), ...progressFields(event.p), status: 'downloading' }
    case 'downloaded': {
      const info = event.info
      let next = without(state, [...PROGRESS_KEYS, 'error'])
      if (info && isVersion(info.version) && info.version !== state.version) next = { ...without(next, RELEASE_KEYS), ...releaseFields(info) }
      return { ...next, status: 'ready', percent: 100 }
    }
    case 'cancelled':
      return { ...without(state, PROGRESS_KEYS), status: 'available' }
    case 'check-error':
      if (busy || state.status === 'available') return { ...state, lastCheck: now }
      return { ...state, status: 'error', error: validError(event.error, 'failed'), lastCheck: now }
    case 'download-error':
      return { ...without(state, PROGRESS_KEYS), status: 'error', error: validError(event.error, 'failed') }
    case 'install-error':
      return { ...state, status: 'ready', error: { code: 'install-failed', message: ERROR_TEXT['install-failed'] } }
    case 'prefs': {
      const autoDownload = event.autoDownload === true
      return state.autoDownload === autoDownload ? state : { ...state, autoDownload }
    }
    default:
      return state
  }
}

/** Is an automatic check due? Every 4 h; 30 min after an offline / rate-limited failure; never during one. */
function checkDue({ status, lastAttemptAt, lastErrorCode, now }) {
  if (status === 'checking' || status === 'downloading') return false
  if (typeof lastAttemptAt !== 'number' || !Number.isFinite(lastAttemptAt)) return true
  const wait = lastErrorCode === 'offline' || lastErrorCode === 'rate-limited' ? CHECK_RETRY_MS : CHECK_EVERY_MS
  return now - lastAttemptAt >= wait
}

// ---- persistence (userData/updater.json) ----

/** updates:setPrefs argument → { autoDownload } | null. Other keys are ignored. */
function parsePrefsArg(arg) {
  if (!arg || typeof arg !== 'object' || Array.isArray(arg) || typeof arg.autoDownload !== 'boolean') return null
  return { autoDownload: arg.autoDownload }
}

/**
 * userData/updater.json (text or parsed) → { autoDownload, attempt?, rejected? }. Anything odd falls back to the
 * defaults; `rejected` (see rememberRejected) is present only when it holds a valid entry.
 */
function parseUpdaterFile(raw) {
  let o = raw
  if (typeof raw === 'string') {
    try {
      o = JSON.parse(raw)
    } catch {
      o = null
    }
  }
  const out = { autoDownload: true }
  if (!o || typeof o !== 'object' || Array.isArray(o)) return out
  if (typeof o.autoDownload === 'boolean') out.autoDownload = o.autoDownload
  const a = o.attempt
  if (a && typeof a === 'object' && isVersion(a.version) && isVersion(a.from) && typeof a.at === 'number' && Number.isFinite(a.at) && a.at >= 0) {
    out.attempt = { version: a.version, from: a.from, at: a.at }
  }
  const rejected = parseRejected(o.rejected)
  if (rejected.length) out.rejected = rejected
  return out
}

/** The updater.json object to write: { v: 1, autoDownload, attempt?, rejected? } (empty / invalid parts left out). */
function updaterFileData(file) {
  const f = file && typeof file === 'object' ? file : {}
  const rejected = parseRejected(f.rejected)
  return {
    v: 1,
    autoDownload: f.autoDownload !== false,
    ...(f.attempt ? { attempt: f.attempt } : {}),
    ...(rejected.length ? { rejected } : {}),
  }
}

// ---- refused update files (persisted: the same file is never downloaded automatically again) ----

/** Our verifier's refusal reasons for a file that is NOT the author's update → error 'signature'. */
const SIGNATURE_REFUSED_REASONS = ['not-signed', 'hash-mismatch', 'other-signer', 'wrong-version', 'not-newer', 'wrong-product', 'not-installer', 'changed']
/** Reasons where the check could not decide → error 'signature-unverified' (retried; never presented as a forgery). */
const SIGNATURE_UNVERIFIED_REASONS = ['bad-chain', 'verify-failed', 'no-pins', 'policy', 'no-file', 'inactive']
const SIGNATURE_REASONS = [...SIGNATURE_REFUSED_REASONS, ...SIGNATURE_UNVERIFIED_REASONS]
const REJECTED_MAX = 5
/** A file the check could not decide on is downloaded automatically again only after this long (one try a day). */
const UNVERIFIED_RETRY_MS = 24 * 60 * 60_000
/** latest.yml sha512: base64 of 64 bytes. */
const SHA512_RE = /^[A-Za-z0-9+/]{86}==$/

function isSha512(v) {
  return typeof v === 'string' && SHA512_RE.test(v)
}

/** 'signature' (refused file) | 'signature-unverified' (the check could not decide). An unknown reason counts as refused. */
function signatureErrorCode(reason) {
  return SIGNATURE_UNVERIFIED_REASONS.includes(reason) ? 'signature-unverified' : 'signature'
}

/** The reason in our verifier's "sanovids-signature:<reason>" (electron-updater puts it in its error message), or ''. */
function signatureReasonOf(text) {
  const m = typeof text === 'string' ? /sanovids-signature:([a-z-]{1,40})/.exec(text) : null
  return m && SIGNATURE_REASONS.includes(m[1]) ? m[1] : ''
}

/** updater.json `rejected` → [{ version, sha512, reason, at }] (valid entries only, at most 5, the latest kept). */
function parseRejected(raw) {
  if (!Array.isArray(raw)) return []
  const out = []
  for (const e of raw) {
    if (!e || typeof e !== 'object' || Array.isArray(e)) continue
    if (!isVersion(e.version) || !isSha512(e.sha512) || !SIGNATURE_REASONS.includes(e.reason)) continue
    if (typeof e.at !== 'number' || !Number.isFinite(e.at) || e.at < 0) continue
    out.push({ version: e.version, sha512: e.sha512, reason: e.reason, at: e.at })
  }
  return out.slice(-REJECTED_MAX)
}

/** The sha512 checksums an UpdateInfo (latest.yml) announces: every file's, plus the legacy top-level one (valid only, ≤ 8). */
function offerHashes(info) {
  const out = []
  const add = (h) => {
    if (isSha512(h) && !out.includes(h) && out.length < 8) out.push(h)
  }
  if (info && typeof info === 'object') {
    if (Array.isArray(info.files)) for (const f of info.files) if (f && typeof f === 'object') add(f.sha512)
    add(info.sha512)
  }
  return out
}

/** `list` + the refused file { version, sha512, reason } (an entry for the same file is replaced). Invalid → `list` unchanged. */
function rememberRejected(list, entry, now) {
  const kept = parseRejected(list)
  const e = entry && typeof entry === 'object' ? entry : {}
  const next = parseRejected([{ version: e.version, sha512: e.sha512, reason: e.reason, at: now }])
  if (!next.length) return kept
  return [...kept.filter((k) => k.sha512 !== next[0].sha512), next[0]].slice(-REJECTED_MAX)
}

/** `list` without the entries for these files (a manual "Thử lại" retries them). */
function forgetRejected(list, hashes) {
  const hs = Array.isArray(hashes) ? hashes.filter(isSha512) : []
  return parseRejected(list).filter((e) => !hs.includes(e.sha512))
}

/**
 * The entry that keeps an offered file from downloading automatically, or null. Matched by checksum only: a re-uploaded,
 * correctly signed file under the same version downloads normally. A refused file stays refused; a file the check could
 * not decide on is tried again UNVERIFIED_RETRY_MS later.
 */
function findRejected(list, hashes, now) {
  const hs = Array.isArray(hashes) ? hashes.filter(isSha512) : []
  if (!hs.length) return null
  const entries = parseRejected(list).reverse()
  for (const e of entries) {
    if (!hs.includes(e.sha512)) continue
    if (signatureErrorCode(e.reason) === 'signature') return e
    const age = now - e.at
    if (age >= 0 && age < UNVERIFIED_RETRY_MS) return e
  }
  return null
}

/**
 * What this launch makes of the install attempt recorded before the last quit:
 *   notice  { kind: 'updated', from, version } | { kind: 'install-failed', version } | null
 *   keep    true = leave the attempt in updater.json for the next launch (this one started while the installer may still
 *           be running: still the old version, less than INSTALL_GRACE_MS after the quit); else the caller clears it.
 */
function startupAttempt(file, current, now) {
  const a = file && file.attempt
  if (!a || !isVersion(a.version) || !isVersion(current)) return { notice: null, keep: false }
  if (compareVersions(current, a.version) >= 0) return { notice: { kind: 'updated', from: a.from, version: current }, keep: false }
  if (current !== a.from) return { notice: null, keep: false }
  const age = now - a.at
  if (age >= 0 && age < INSTALL_GRACE_MS) return { notice: null, keep: true }
  if (age >= 0 && age < INSTALL_NOTICE_MS) return { notice: { kind: 'install-failed', version: a.version }, keep: false }
  return { notice: null, keep: false }
}

/** startupAttempt(...).notice */
function startupNotice(file, current, now) {
  return startupAttempt(file, current, now).notice
}

/** One line of userData/logs/updater.log. */
function logLine(level, message, date) {
  const d = date instanceof Date ? date : new Date(typeof date === 'number' ? date : Date.now())
  const iso = Number.isFinite(d.getTime()) ? d.toISOString() : new Date(0).toISOString()
  const msg = String(message).replace(/\r\n|\r|\n/g, ' ⏎ ')
  return `${iso} [${level}] ${msg}`.slice(0, LOG_LINE_MAX)
}

// ---- code signature (electron/signature.cjs runs it; the updater and the app's self-check judge with it) ----

const SIGNATURE_MARK = 'SVSIG'
const SIGNER_PINS_MAX = 8
const SIGNER_MAX = 200
const THUMBPRINT_RE = /^[0-9A-F]{40}$/

/**
 * Windows PowerShell 5.1, one line, run with -Command. It reads the file path ONLY from env SANOVIDS_SIG_PATH (never
 * from the command line) and writes one JSON object between two SVSIG markers, every non-ASCII char \u-escaped (so the
 * console code page cannot garble a name). Never a double quote, a newline or a backtick in it (tested): nothing a
 * command line could re-split. Its fields feed judgeSignature; StatusMessage / Subject are localized and never read.
 *  - First a check that works in ConstrainedLanguage (AppLocker / WDAC script enforcement): there every method call
 *    below would fail with no output at all, so it says so ({ error: 'clm' } → reason 'policy') and stops.
 *  - ProductName / ProductVersion of the file's VersionInfo (inside the signed PE, so authenticated by the signature):
 *    the updater requires the installer to be the offered, newer version of this very app (installerIdentityProblem).
 *  - A timestamped signature: our extra chain build ignores NotTimeValid (WinVerifyTrust already judged the certificate's
 *    validity at the RFC 3161 signing time; a PC clock that is wrong, or a certificate that expired later, must not
 *    refuse a genuine file). judgeSignature accepts NotTimeValid only next to a timestamp.
 */
const SIGNATURE_SCRIPT = [
  "$ErrorActionPreference='Stop'",
  "$ProgressPreference='SilentlyContinue'",
  `if($ExecutionContext.SessionState.LanguageMode -ne 'FullLanguage'){ Write-Output ('${SIGNATURE_MARK}'+(@{v=1;status=-1;error='clm'}|ConvertTo-Json -Compress)+'${SIGNATURE_MARK}'); exit }`,
  '$r=[ordered]@{v=1;status=-1;sigType=$null;thumbprint=$null;signer=$null;tsThumbprint=$null;chainOk=$false;chainStatus=@();chainLen=0;hresult=$null;productVersion=$null;productName=$null;error=$null}',
  "try { $p=$env:SANOVIDS_SIG_PATH; if([string]::IsNullOrEmpty($p)){throw 'no-path'}",
  '$s=Get-AuthenticodeSignature -LiteralPath $p',
  '$r.status=[int]$s.Status',
  '$r.sigType=[string]$s.SignatureType',
  // `try {…} catch {…}` is ONE statement: no "; " may separate them. A VersionInfo problem only leaves both fields null.
  'try { $vi=(Get-Item -LiteralPath $p).VersionInfo; $r.productVersion=[string]$vi.ProductVersion; $r.productName=[string]$vi.ProductName } catch { $r.productVersion=$null }',
  "$f=$s.GetType().GetField('win32Error',[System.Reflection.BindingFlags]'NonPublic,Instance')",
  "if($null -ne $f){$r.hresult='0x{0:X8}' -f [uint32]$f.GetValue($s)}",
  'if($null -ne $s.TimeStamperCertificate){$r.tsThumbprint=$s.TimeStamperCertificate.Thumbprint}',
  '$c=$s.SignerCertificate',
  'if($null -ne $c){ $r.thumbprint=$c.Thumbprint; $r.signer=$c.GetNameInfo([System.Security.Cryptography.X509Certificates.X509NameType]::SimpleName,$false)',
  '$ch=New-Object System.Security.Cryptography.X509Certificates.X509Chain',
  '$ch.ChainPolicy.RevocationMode=[System.Security.Cryptography.X509Certificates.X509RevocationMode]::NoCheck',
  "$fl='AllowUnknownCertificateAuthority'",
  "if($null -ne $r.tsThumbprint){$fl+=',IgnoreNotTimeValid'}",
  '$ch.ChainPolicy.VerificationFlags=[System.Security.Cryptography.X509Certificates.X509VerificationFlags]$fl',
  "[void]$ch.ChainPolicy.ApplicationPolicy.Add((New-Object System.Security.Cryptography.Oid '1.3.6.1.5.5.7.3.3'))",
  '$r.chainOk=$ch.Build($c)',
  '$r.chainStatus=@($ch.ChainStatus|ForEach-Object{[string]$_.Status})',
  // `try {…} catch {…}` is ONE statement: no "; " may separate them.
  '$r.chainLen=$ch.ChainElements.Count } } catch { $r.error=$_.Exception.GetType().FullName }',
  '$j=$r|ConvertTo-Json -Compress',
  '$sb=New-Object System.Text.StringBuilder',
  "foreach($x in $j.ToCharArray()){ if([int]$x -gt 126){[void]$sb.AppendFormat('\\u{0:x4}',[int]$x)} else {[void]$sb.Append($x)} }",
  `[Console]::Out.Write('${SIGNATURE_MARK}'+$sb.ToString()+'${SIGNATURE_MARK}')`,
].join('; ')

/**
 * powershell.exe arguments: the script as a literal -Command. No -EncodedCommand and no -ExecutionPolicy Bypass (both
 * are classic endpoint-protection heuristics); Get-AuthenticodeSignature runs under any execution policy.
 */
function powershellArgs() {
  return ['-NoLogo', '-NoProfile', '-NonInteractive', '-InputFormat', 'None', '-Command', SIGNATURE_SCRIPT]
}

/**
 * Variables that change which code runs inside powershell.exe: a CLR profiler DLL (COR_ENABLE_PROFILING /
 * COR_PROFILER / COR_PROFILER_PATH…) or CLR / .NET runtime knobs (COMPlus_* / DOTNET_* / CORECLR_*) could make the
 * verifier print whatever an injected DLL wants. Dropped by prefix (case-insensitive). Policy markers are kept.
 */
const POWERSHELL_ENV_DROPPED_PREFIXES = ['cor_', 'complus_', 'dotnet_', 'coreclr_']

/**
 * The child's environment: a copy of `baseEnv` without PSModulePath (a PowerShell 7 value breaks module loading in
 * Windows PowerShell 5.1) and without the code-injection variables above, plus SANOVIDS_SIG_PATH = the file. Names are
 * matched case-insensitively (Windows env).
 */
function powershellEnv(baseEnv, file) {
  const out = {}
  const src = baseEnv && typeof baseEnv === 'object' ? baseEnv : {}
  for (const key of Object.keys(src)) {
    const lower = key.toLowerCase()
    if (lower === 'psmodulepath' || lower === 'sanovids_sig_path') continue
    if (POWERSHELL_ENV_DROPPED_PREFIXES.some((p) => lower.startsWith(p))) continue
    if (typeof src[key] === 'string') out[key] = src[key]
  }
  out.SANOVIDS_SIG_PATH = String(file)
  return out
}

/**
 * package.json sanovids.signers → the pinned SHA-1 thumbprints: whitespace removed, upper-cased, 40 hex chars only,
 * deduped, at most 8. Not an array → [] (no pin: every check fails closed).
 */
function parseSignerPins(raw) {
  if (!Array.isArray(raw)) return []
  const out = []
  for (const item of raw) {
    if (typeof item !== 'string') continue
    const pin = item.replace(/\s+/g, '').toUpperCase()
    if (THUMBPRINT_RE.test(pin) && !out.includes(pin)) out.push(pin)
    if (out.length >= SIGNER_PINS_MAX) break
  }
  return out
}

/** ChainStatus as strings (a bare value becomes a one-item list; PowerShell's {value: [...]} array wrapper unwrapped). */
function chainList(v) {
  if (v == null) return []
  if (Array.isArray(v)) return v.map((s) => String(s))
  if (typeof v === 'object' && Array.isArray(v.value)) return v.value.map((s) => String(s))
  return [String(v)]
}

const strOrNull = (v) => (typeof v === 'string' ? v : null)

/** Display name of a signer: control characters removed, at most 200 chars ('' when there is none). */
function cleanSigner(v) {
  return typeof v === 'string' ? v.replace(/[\u0000-\u001f\u007f-\u009f]/g, '').slice(0, SIGNER_MAX) : ''
}

/** SIGNATURE_SCRIPT's stdout → the normalized object between the first and the last SVSIG marker, or null. */
function parseSignatureOutput(stdout) {
  if (typeof stdout !== 'string') return null
  const start = stdout.indexOf(SIGNATURE_MARK)
  const end = stdout.lastIndexOf(SIGNATURE_MARK)
  if (start === -1 || end < start + SIGNATURE_MARK.length) return null
  let o
  try {
    o = JSON.parse(stdout.slice(start + SIGNATURE_MARK.length, end))
  } catch {
    return null
  }
  if (!o || typeof o !== 'object' || Array.isArray(o)) return null
  const productVersion = cleanText(o.productVersion, VERSION_MAX)
  const productName = cleanText(o.productName, SIGNER_MAX)
  return {
    v: typeof o.v === 'number' ? o.v : null,
    status: typeof o.status === 'number' ? o.status : null,
    sigType: strOrNull(o.sigType),
    thumbprint: typeof o.thumbprint === 'string' ? o.thumbprint.toUpperCase() : null,
    signer: strOrNull(o.signer),
    tsThumbprint: strOrNull(o.tsThumbprint),
    chainOk: o.chainOk === true,
    chainStatus: chainList(o.chainStatus),
    chainLen: typeof o.chainLen === 'number' ? o.chainLen : null,
    hresult: strOrNull(o.hresult),
    error: o.error == null ? null : String(o.error),
    // Only when the script read them (an older script, a non-PE file or no VersionInfo: absent).
    ...(productVersion ? { productVersion } : {}),
    ...(productName ? { productName } : {}),
  }
}

/** A VersionInfo string: trimmed, control characters removed, at most `max` chars; '' / not a string → ''. */
function cleanText(v, max) {
  return typeof v === 'string' ? v.replace(/[\u0000-\u001f\u007f-\u009f]/g, '').trim().slice(0, max) : ''
}

/**
 * The verdict on a parsed signature (parseSignatureOutput) against the pinned thumbprints. Rows IN ORDER; the status is
 * looked at before the thumbprint because a HashMismatch file still reports its (pinned) signer:
 *   1 no pins → unknown/no-pins · 2a PowerShell in ConstrainedLanguage ({ error: 'clm' }) → unknown/policy ·
 *   2 no usable output → unknown/verify-failed · 3 NotSigned → unsigned/not-signed ·
 *   4 HashMismatch → tampered/hash-mismatch · 5 not Authenticode or no thumbprint → unknown/verify-failed ·
 *   6 thumbprint not pinned → other-signer · 7a Valid (machine trusts the cert) / 7b the genuine self-signed case
 *   (UnknownError 0x800B0109 CERT_E_UNTRUSTEDROOT, chain = the one self-signed cert) → signed/ok ·
 *   8 anything else → unknown/bad-chain.
 * In 7a / 7b the extra chain may also report NotTimeValid when the signature is timestamped (WinVerifyTrust judged the
 * certificate's validity at the signing time; only the PC clock / a later expiry makes the chain say so).
 * The common name is never trusted: an impostor with the author's exact CN differs by thumbprint (row 6).
 * → { ok, status, reason, thumbprint?, signer?, timestamped, productVersion?, productName? } (the last two only when
 * signed and read by the script: the updater checks them, nobody else).
 */
function judgeSignature(parsed, pins) {
  const pinList = parseSignerPins(pins)
  const p = parsed && typeof parsed === 'object' ? parsed : null
  const timestamped = !!p && p.tsThumbprint != null
  const verdict = (ok, status, reason, extra) => ({ ok, status, reason, ...(extra || {}), timestamped })
  if (!pinList.length) return verdict(false, 'unknown', 'no-pins')
  if (p && p.v === 1 && p.error === 'clm') return { ...verdict(false, 'unknown', 'policy'), timestamped: false }
  if (!p || p.v !== 1 || p.error != null || !Number.isInteger(p.status)) return { ...verdict(false, 'unknown', 'verify-failed'), timestamped: false }
  const thumb = typeof p.thumbprint === 'string' ? p.thumbprint.toUpperCase() : ''
  const who = THUMBPRINT_RE.test(thumb) ? { thumbprint: thumb, ...(cleanSigner(p.signer) ? { signer: cleanSigner(p.signer) } : {}) } : {}
  if (p.status === 2) return verdict(false, 'unsigned', 'not-signed')
  if (p.status === 3) return verdict(false, 'tampered', 'hash-mismatch', who)
  if (p.sigType !== 'Authenticode' || !THUMBPRINT_RE.test(thumb)) return verdict(false, 'unknown', 'verify-failed')
  if (!pinList.includes(thumb)) return verdict(false, 'other-signer', 'other-signer', who)
  const chain = chainList(p.chainStatus)
  const allowed = timestamped ? ['UntrustedRoot', 'NotTimeValid'] : ['UntrustedRoot']
  const chainFine = chain.every((s) => allowed.includes(s))
  const trusted = p.status === 0 && (p.hresult == null || p.hresult === '0x00000000') && p.chainOk === true && chainFine
  // 7b: exactly ['UntrustedRoot'] (+ 'NotTimeValid' when timestamped), each once, from a one-certificate chain.
  const selfSigned =
    p.status === 1 &&
    p.hresult === '0x800B0109' &&
    p.chainOk === true &&
    chainFine &&
    chain.includes('UntrustedRoot') &&
    new Set(chain).size === chain.length &&
    p.chainLen === 1
  if (trusted || selfSigned) {
    const product = {
      ...(typeof p.productVersion === 'string' && p.productVersion ? { productVersion: p.productVersion } : {}),
      ...(typeof p.productName === 'string' && p.productName ? { productName: p.productName } : {}),
    }
    return verdict(true, 'signed', 'ok', { ...who, ...product })
  }
  return verdict(false, 'unknown', 'bad-chain', who)
}

/**
 * Below this size a pinned-signed file is not an NSIS installer of the app (Electron alone compresses to ~80 MB): the
 * uninstaller and elevate.exe — also signed by the author, and harmful when run as "the update" — are far smaller.
 */
const INSTALLER_MIN_BYTES = 20 * 1024 * 1024

/**
 * A pinned-signed file must also BE the update that was offered (anti-rollback / anti-swap): its signed VersionInfo
 * ProductVersion equals the offered version, which is newer than the running one; its ProductName is this app's; and
 * it is installer-sized. `verdict` = judgeSignature's (ok) verdict; expected = { version, current, appName, size }.
 * → '' when it is, else 'wrong-version' | 'not-newer' | 'wrong-product' | 'not-installer'.
 */
function installerIdentityProblem(verdict, expected) {
  const v = verdict && typeof verdict === 'object' ? verdict : {}
  const e = expected && typeof expected === 'object' ? expected : {}
  const pv = typeof v.productVersion === 'string' ? v.productVersion : ''
  if (!isVersion(pv) || !isVersion(e.version) || pv !== e.version) return 'wrong-version'
  if (!isVersion(e.current) || compareVersions(pv, e.current) <= 0) return 'not-newer'
  if (typeof e.appName !== 'string' || e.appName === '' || v.productName !== e.appName) return 'wrong-product'
  if (typeof e.size !== 'number' || !Number.isFinite(e.size) || e.size < INSTALLER_MIN_BYTES) return 'not-installer'
  return ''
}

/**
 * Same path, size and mtime as the verified installer (`stat` from fs.statSync; anything missing → false). The cheap
 * first look in the app 'quit' event; sameVerifiedFile decides.
 */
function sameVerifiedMeta(verified, stat, file) {
  if (!verified || typeof verified !== 'object' || !stat || typeof stat !== 'object') return false
  if (typeof file !== 'string' || file === '' || verified.file !== file) return false
  return typeof stat.size === 'number' && verified.size === stat.size && typeof stat.mtimeMs === 'number' && verified.mtimeMs === stat.mtimeMs
}

/**
 * Is the file on disk still the very one that was verified? Same path, size and mtime AND the same content: `sha512`
 * (base64, hashed again right now) equals the hash taken when it passed. Size + mtime alone can be faked (same size,
 * LastWriteTime put back). Used synchronously in the app 'quit' event and right before quitAndInstall.
 */
function sameVerifiedFile(verified, stat, file, sha512) {
  if (!sameVerifiedMeta(verified, stat, file)) return false
  return isSha512(verified.sha512) && sha512 === verified.sha512
}

/**
 * electron-updater's cached blockmap (<cache>/current.blockmap) for an installer at <cache>/pending/<name>, or null when
 * the installer is not in a "pending" folder. It describes the NEXT version once a download completes: when that
 * installer is refused or not installed, it no longer matches the cached installer.exe and must go (else the next
 * differential download builds a wrong file and falls back to a full one).
 */
function cachedBlockmapFile(installerPath, pathMod) {
  if (typeof installerPath !== 'string' || installerPath === '' || !pathMod) return null
  const pending = pathMod.dirname(installerPath)
  if (pathMod.basename(pending).toLowerCase() !== 'pending') return null
  const cache = pathMod.dirname(pending)
  if (cache === pending) return null
  return pathMod.join(cache, 'current.blockmap')
}

module.exports = {
  RELEASES_URL,
  FEED,
  NOTES_MAX,
  INSTALL_GRACE_MS,
  ERROR_TEXT,
  isVersion,
  compareVersions,
  resolveProfileDir,
  appUserModelId,
  detectKind,
  placement,
  portableRelaunch,
  mapUpdaterError,
  notesToText,
  normalizeInfo,
  initialState,
  reduceUpdateState,
  checkDue,
  parsePrefsArg,
  parseUpdaterFile,
  updaterFileData,
  startupAttempt,
  startupNotice,
  logLine,
  SIGNATURE_REFUSED_REASONS,
  SIGNATURE_UNVERIFIED_REASONS,
  REJECTED_MAX,
  UNVERIFIED_RETRY_MS,
  isSha512,
  signatureErrorCode,
  signatureReasonOf,
  offerHashes,
  rememberRejected,
  forgetRejected,
  findRejected,
  SIGNATURE_SCRIPT,
  powershellArgs,
  powershellEnv,
  parseSignerPins,
  parseSignatureOutput,
  judgeSignature,
  INSTALLER_MIN_BYTES,
  installerIdentityProblem,
  sameVerifiedMeta,
  sameVerifiedFile,
  cachedBlockmapFile,
}
