// SanoVids — pure rules of the desktop auto-updater (electron/updater.cjs). Unit-tested by
// src/lib/__tests__/updaterRules.test.ts.
//
// No require at all: not 'electron', not any npm package. In the packaged app.asar, electron-updater's own helpers
// (semver…) are nested under node_modules/electron-updater and cannot be resolved from electron/, so versions are
// compared here by hand. Everything is plain data in, plain data out (paths go through an injected node:path flavour).
'use strict'

/** The public download page (opened by main only; the renderer never sends a URL). */
const RELEASES_URL = 'https://github.com/JameSteven404/sanovids-releases/releases/latest'
/**
 * For tests and logs only: the real feed is resources/app-update.yml, generated by electron-builder from
 * package.json build.publish. The app never calls setFeedURL.
 */
const FEED = Object.freeze({ provider: 'github', owner: 'JameSteven404', repo: 'sanovids-releases' })

const NOTES_MAX = 8000 // = src/lib/updateTypes.ts UPDATE_NOTES_MAX
const VERSION_MAX = 64
const RELEASE_DATE_MAX = 40
const LOG_LINE_MAX = 4000
const PROFILE_DIR_MAX = 240
const INSTALL_NOTICE_MS = 7 * 24 * 60 * 60_000
const CHECK_EVERY_MS = 4 * 60 * 60_000
const CHECK_RETRY_MS = 30 * 60_000

const VERSION_RE = /^\d+\.\d+\.\d+([-+.][0-9A-Za-z.-]+)?$/

const ERROR_CODES = ['offline', 'no-release', 'rate-limited', 'checksum', 'signature', 'disk', 'install-failed', 'failed']

/** Fixed Vietnamese texts: raw error text, stacks, XML or headers never reach the renderer. */
const ERROR_TEXT = {
  offline: 'Không kết nối được máy chủ cập nhật.',
  'no-release': 'Chưa tìm thấy bản cập nhật nào trên trang tải về.',
  'rate-limited': 'Máy chủ cập nhật đang bận.',
  checksum: 'File cập nhật tải về bị lỗi (sai mã kiểm tra) nên đã bị bỏ.',
  signature: 'File cập nhật không có chữ ký hợp lệ nên đã bị từ chối.',
  disk: 'Ổ đĩa không đủ chỗ để tải bản cập nhật.',
  'install-failed': 'Không khởi động được trình cài bản cập nhật.',
}
const FAILED_TEXT = { check: 'Không kiểm tra được bản cập nhật.', download: 'Tải bản cập nhật bị lỗi.' }

const NO_RELEASE_CODES = new Set([
  'HTTP_ERROR_404',
  'ERR_XML_MISSED_ELEMENT',
  'ERR_UPDATER_NO_PUBLISHED_VERSIONS',
  'ERR_UPDATER_LATEST_VERSION_NOT_FOUND',
  'ERR_UPDATER_CHANNEL_FILE_NOT_FOUND',
])
const OFFLINE_RE = /net::ERR_|ENOTFOUND|ECONNRESET|ECONNREFUSED|ETIMEDOUT|EAI_AGAIN/

// ---- versions ----

/** "1.2.3", "0.5.0-beta.1" (at most 64 chars). */
function isVersion(v) {
  return typeof v === 'string' && v.length <= VERSION_MAX && VERSION_RE.test(v)
}

function parseVersion(v) {
  if (!isVersion(v)) return null
  const m = /^(\d+)\.(\d+)\.(\d+)(.*)$/.exec(v)
  // Build metadata ("+abc") never changes the order; anything else after x.y.z is a pre-release.
  const rest = m[4].replace(/\+.*$/, '')
  return { nums: [Number(m[1]), Number(m[2]), Number(m[3])], pre: rest ? rest.replace(/^[-.]/, '').split('.') : [] }
}

function compareIds(a, b) {
  const an = /^\d+$/.test(a)
  const bn = /^\d+$/.test(b)
  if (an && bn) return Math.sign(Number(a) - Number(b))
  if (an !== bn) return an ? -1 : 1 // numeric identifiers sort below alphanumeric ones (semver)
  return a < b ? -1 : a > b ? 1 : 0
}

/**
 * -1 | 0 | 1 on numeric x.y.z; a pre-release ("0.5.0-beta") sorts below its plain version ("0.5.0").
 * Something that is not a version sorts below every version (two of them are equal).
 */
function compareVersions(a, b) {
  const pa = parseVersion(a)
  const pb = parseVersion(b)
  if (!pa || !pb) return pa ? 1 : pb ? -1 : 0
  for (let i = 0; i < 3; i++) if (pa.nums[i] !== pb.nums[i]) return pa.nums[i] < pb.nums[i] ? -1 : 1
  if (!pa.pre.length || !pb.pre.length) return pa.pre.length === pb.pre.length ? 0 : pa.pre.length ? -1 : 1
  for (let i = 0; i < Math.max(pa.pre.length, pb.pre.length); i++) {
    if (i >= pa.pre.length) return -1
    if (i >= pb.pre.length) return 1
    const c = compareIds(pa.pre[i], pb.pre[i])
    if (c) return c
  }
  return 0
}

// ---- data folder (test-only isolation) ----

function profileKey(p, pathMod) {
  let r = pathMod.resolve(p)
  const root = pathMod.parse(r).root
  if (r.length > root.length) r = r.replace(/[\\/]+$/, '')
  return pathMod.sep === '\\' ? r.toLowerCase() : r
}

/** Why `candidate` may not be used as the data folder ('' when it may). */
function profileDirProblem(candidate, real, pathMod) {
  if (candidate.length > PROFILE_DIR_MAX) return `longer than ${PROFILE_DIR_MAX} characters`
  if (candidate.includes('\u0000')) return 'contains a NUL character'
  if (!pathMod.isAbsolute(candidate)) return 'not an absolute path'
  const resolved = pathMod.resolve(candidate)
  const root = pathMod.parse(resolved).root
  if (resolved.replace(/[\\/]+$/, '') === root.replace(/[\\/]+$/, '')) return 'a filesystem root'
  const key = profileKey(resolved, pathMod)
  const realKey = profileKey(real, pathMod)
  if (key === realKey) return 'it is the real SanoVids data folder'
  if (key.startsWith(realKey + pathMod.sep)) return 'it is inside the real SanoVids data folder'
  return ''
}

/**
 * The userData folder. Real users: %APPDATA%\SanoVids (or <appData>\<appName> for another product name).
 * Agent / E2E tests only: SANOVIDS_PROFILE_DIR (env), else `sanovidsTestProfileDir` baked into the packaged
 * package.json by test builds. Such a folder must be absolute, not a root, and never the real folder or inside it:
 * otherwise { ok: false } and the app refuses to start (fail closed).
 * → { ok: true, dir, source: 'env' | 'baked' | 'default' } | { ok: false, error }
 */
function resolveProfileDir({ env, baked, appData, appName, pathMod }) {
  const real = pathMod.join(appData, 'SanoVids')
  const fromEnv = typeof env === 'string' && env !== ''
  const candidate = fromEnv ? env : typeof baked === 'string' && baked !== '' ? baked : null
  if (candidate === null) {
    if (appName === 'SanoVids') return { ok: true, dir: real, source: 'default' }
    let leaf = String(appName || '').replace(/[^A-Za-z0-9._-]/g, '_')
    if (/^\.*$/.test(leaf)) leaf = 'SanoVids-other' // never '', '.' or '..'
    return { ok: true, dir: pathMod.join(appData, leaf), source: 'default' }
  }
  const problem = profileDirProblem(candidate, real, pathMod)
  if (problem) return { ok: false, error: `SANOVIDS_PROFILE_DIR / sanovidsTestProfileDir is invalid: ${problem}` }
  return { ok: true, dir: pathMod.resolve(candidate), source: fromEnv ? 'env' : 'baked' }
}

/** Windows taskbar / notification identity: the real app keeps com.sanovids.app, test builds get their own. */
function appUserModelId(appName) {
  if (appName === 'SanoVids') return 'com.sanovids.app'
  return 'com.sanovids.test.' + String(appName || '').toLowerCase().replace(/[^a-z0-9]/g, '')
}

/**
 * 'dev'       not packaged (`electron .`): never checks;
 * 'portable'  the portable .exe (PORTABLE_EXECUTABLE_FILE), win-unpacked or a copied exe: check only;
 * 'installer' an NSIS install (its uninstaller sits next to the exe): check, download, install.
 */
function detectKind({ platform, isPackaged, portableFile, execPath, appName, exists, pathMod }) {
  if (!isPackaged) return 'dev'
  if (typeof portableFile === 'string' && portableFile !== '') return 'portable'
  if (platform === 'win32' && typeof execPath === 'string' && execPath !== '') {
    let found = false
    try {
      found = !!exists(pathMod.join(pathMod.dirname(execPath), `Uninstall ${appName}.exe`))
    } catch {
      found = false
    }
    if (found) return 'installer'
  }
  return 'portable'
}

// ---- errors ----

/** Error of electron-updater → { code, message } with a fixed Vietnamese message. phase: 'check' | 'download' | 'install'. */
function mapUpdaterError(err, phase) {
  const message = (code) => ERROR_TEXT[code] || FAILED_TEXT[phase] || FAILED_TEXT.check
  // An install that did not start is always 'install-failed' (the state goes back to 'ready' with it).
  if (phase === 'install') return { code: 'install-failed', message: message('install-failed') }
  const code = err && typeof err.code === 'string' ? err.code : ''
  const text = err && typeof err.message === 'string' ? err.message : typeof err === 'string' ? err : ''
  const all = `${code} ${text}`
  let out = 'failed'
  // Offline first: electron-updater wraps some network failures in "not found" codes (e.g. the latest.yml fetch).
  if (OFFLINE_RE.test(all)) out = 'offline'
  else if (NO_RELEASE_CODES.has(code) || /No published versions/i.test(text)) out = 'no-release'
  else if (code === 'HTTP_ERROR_429' || code === 'HTTP_ERROR_403') out = 'rate-limited'
  else if (code === 'ERR_CHECKSUM_MISMATCH' || /sha512 checksum mismatch/i.test(text)) out = 'checksum'
  else if (code === 'ERR_UPDATER_INVALID_SIGNATURE') out = 'signature'
  else if (code === 'ENOSPC' || /\bENOSPC\b/.test(text)) out = 'disk'
  return { code: out, message: message(out) }
}

// ---- release notes ----

const HTML_TAG_RE = /<\/?[a-z][^>]*>/i
const ENTITY_RE = /&(#x[0-9a-f]{1,6}|#\d{1,7}|amp|lt|gt|quot|apos|nbsp);/gi
const NAMED_ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' }

function decodeEntities(s) {
  // One pass: "&amp;lt;" becomes "&lt;" (text), never "<".
  return s.replace(ENTITY_RE, (whole, body) => {
    const lower = body.toLowerCase()
    if (lower[0] !== '#') return NAMED_ENTITIES[lower]
    const cp = lower[1] === 'x' ? parseInt(lower.slice(2), 16) : parseInt(lower.slice(1), 10)
    if (!Number.isFinite(cp) || cp <= 0 || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return ''
    return String.fromCodePoint(cp)
  })
}

/** GitHub-rendered HTML → markdown-ish plain text (entities decoded last, so they always stay text). */
function htmlToText(s) {
  return decodeEntities(
    s
      .replace(/<(script|style)\b[\s\S]*?<\/\1\s*>/gi, '')
      // Whitespace between two tags means nothing in HTML (only the tags below break lines there). Newlines inside text
      // are kept: markdown notes with one inline tag ("- <b>x</b>") also land here and must keep their lines.
      .replace(/>\s+</g, '><')
      .replace(/[ \t\f\v]+/g, ' ')
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<\/(p|div|li|ul|ol|h[1-6])\s*>/gi, '\n')
      .replace(/<li\b[^>]*>/gi, '- ')
      .replace(/<h[1-6]\b[^>]*>/gi, '## ')
      .replace(/<[^>]*>/g, '')
      .replace(/^ +| +$/gm, ''),
  )
}

function noteText(s) {
  const t = s.replace(/\r\n?/g, '\n')
  return HTML_TAG_RE.test(t) ? htmlToText(t) : t
}

/**
 * releaseNotes of latest.yml / the GitHub feed → PLAIN TEXT (markdown-ish, never HTML), at most 8000 chars.
 * Accepts a string (markdown or HTML) or electron-updater's [{ version, note }] list.
 */
function notesToText(releaseNotes) {
  let text = ''
  if (typeof releaseNotes === 'string') text = noteText(releaseNotes)
  else if (Array.isArray(releaseNotes)) {
    text = releaseNotes
      .filter((r) => r && typeof r === 'object')
      .map((r) => {
        const version = typeof r.version === 'string' ? r.version.slice(0, VERSION_MAX) : ''
        const note = typeof r.note === 'string' ? noteText(r.note) : ''
        return [version, note].filter(Boolean).join('\n')
      })
      .filter(Boolean)
      .join('\n\n')
  }
  text = text
    .replace(/\r/g, '\n')
    .replace(/[\u0000-\u0008\u000b-\u001f\u007f-\u009f]/g, '')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
  if (text.length > NOTES_MAX) {
    let head = text.slice(0, NOTES_MAX - 1)
    const nl = head.lastIndexOf('\n')
    if (nl > 0) head = head.slice(0, nl)
    else if (/[\ud800-\udbff]$/.test(head)) head = head.slice(0, -1)
    text = head.trimEnd() + '…'
  }
  return text
}

/** UpdateInfo of electron-updater → { version, releaseDate?, notes, size? } | null (invalid version: ignore the event). */
function normalizeInfo(info) {
  if (!info || typeof info !== 'object' || !isVersion(info.version)) return null
  const out = { version: info.version, notes: notesToText(info.releaseNotes) }
  if (typeof info.releaseDate === 'string' && info.releaseDate) out.releaseDate = info.releaseDate.slice(0, RELEASE_DATE_MAX)
  const first = Array.isArray(info.files) ? info.files[0] : null
  const size = first && typeof first === 'object' ? first.size : undefined
  if (typeof size === 'number' && Number.isFinite(size) && size >= 0) out.size = size
  return out
}

// ---- state machine (same shapes as src/lib/updateTypes.ts) ----

const PROGRESS_KEYS = ['percent', 'transferred', 'total', 'bytesPerSecond']
const RELEASE_KEYS = ['version', 'releaseDate', 'notes', 'size']

function without(state, keys) {
  const out = { ...state }
  for (const k of keys) delete out[k]
  return out
}

function initialState({ kind, current, autoDownload, notice }) {
  const state = {
    kind,
    current: typeof current === 'string' ? current.slice(0, VERSION_MAX) : '',
    status: kind === 'dev' ? 'unsupported' : 'idle',
    autoDownload: autoDownload !== false,
  }
  if (notice) state.notice = notice
  return state
}

function finiteNonNeg(v) {
  return typeof v === 'number' && Number.isFinite(v) && v >= 0 ? v : undefined
}

function progressFields(p) {
  const o = p && typeof p === 'object' ? p : {}
  const out = {}
  const percent = finiteNonNeg(o.percent)
  if (percent !== undefined) out.percent = Math.min(100, percent)
  for (const k of ['transferred', 'total', 'bytesPerSecond']) {
    const v = finiteNonNeg(o[k])
    if (v !== undefined) out[k] = v
  }
  return out
}

function releaseFields(info) {
  const out = { version: info.version }
  if (typeof info.releaseDate === 'string' && info.releaseDate) out.releaseDate = info.releaseDate.slice(0, RELEASE_DATE_MAX)
  if (typeof info.notes === 'string') out.notes = info.notes.slice(0, NOTES_MAX)
  const size = finiteNonNeg(info.size)
  if (size !== undefined) out.size = size
  return out
}

function validError(error, fallbackCode) {
  if (error && ERROR_CODES.includes(error.code) && typeof error.message === 'string') {
    return { code: error.code, message: error.message.slice(0, 300) }
  }
  return { code: fallbackCode, message: ERROR_TEXT[fallbackCode] || FAILED_TEXT.check }
}

/**
 * The updater state machine (docs: SPEC A.4). Pure: returns the same object when nothing changes.
 * `event.info` is the output of normalizeInfo; `event.error` the output of mapUpdaterError.
 */
function reduceUpdateState(state, event, now) {
  if (!event || typeof event !== 'object') return state
  const busy = state.status === 'downloading' || state.status === 'ready'
  switch (event.type) {
    case 'checking':
      if (busy) return state
      return { ...without(state, ['error']), status: 'checking' }
    case 'not-available':
      if (busy) return { ...state, lastCheck: now }
      return { ...without(state, [...RELEASE_KEYS, ...PROGRESS_KEYS, 'error']), status: 'none', lastCheck: now }
    case 'available': {
      const info = event.info
      if (!info || !isVersion(info.version)) return state
      if (busy && info.version === state.version) return { ...state, lastCheck: now }
      return { ...without(state, [...RELEASE_KEYS, ...PROGRESS_KEYS, 'error']), ...releaseFields(info), status: 'available', lastCheck: now }
    }
    case 'progress':
      return { ...without(state, [...PROGRESS_KEYS, 'error']), ...progressFields(event.p), status: 'downloading' }
    case 'downloaded': {
      const info = event.info
      let next = without(state, [...PROGRESS_KEYS, 'error'])
      if (info && isVersion(info.version) && info.version !== state.version) next = { ...without(next, RELEASE_KEYS), ...releaseFields(info) }
      return { ...next, status: 'ready', percent: 100 }
    }
    case 'cancelled':
      return { ...without(state, PROGRESS_KEYS), status: 'available' }
    case 'check-error':
      if (busy || state.status === 'available') return { ...state, lastCheck: now }
      return { ...state, status: 'error', error: validError(event.error, 'failed'), lastCheck: now }
    case 'download-error':
      return { ...without(state, PROGRESS_KEYS), status: 'error', error: validError(event.error, 'failed') }
    case 'install-error':
      return { ...state, status: 'ready', error: { code: 'install-failed', message: ERROR_TEXT['install-failed'] } }
    case 'prefs': {
      const autoDownload = event.autoDownload === true
      return state.autoDownload === autoDownload ? state : { ...state, autoDownload }
    }
    default:
      return state
  }
}

/** Is an automatic check due? Every 4 h; 30 min after an offline / rate-limited failure; never during one. */
function checkDue({ status, lastAttemptAt, lastErrorCode, now }) {
  if (status === 'checking' || status === 'downloading') return false
  if (typeof lastAttemptAt !== 'number' || !Number.isFinite(lastAttemptAt)) return true
  const wait = lastErrorCode === 'offline' || lastErrorCode === 'rate-limited' ? CHECK_RETRY_MS : CHECK_EVERY_MS
  return now - lastAttemptAt >= wait
}

// ---- persistence (userData/updater.json) ----

/** updates:setPrefs argument → { autoDownload } | null. Other keys are ignored. */
function parsePrefsArg(arg) {
  if (!arg || typeof arg !== 'object' || Array.isArray(arg) || typeof arg.autoDownload !== 'boolean') return null
  return { autoDownload: arg.autoDownload }
}

/** userData/updater.json (text or parsed) → { autoDownload, attempt? }. Anything odd falls back to the defaults. */
function parseUpdaterFile(raw) {
  let o = raw
  if (typeof raw === 'string') {
    try {
      o = JSON.parse(raw)
    } catch {
      o = null
    }
  }
  const out = { autoDownload: true }
  if (!o || typeof o !== 'object' || Array.isArray(o)) return out
  if (typeof o.autoDownload === 'boolean') out.autoDownload = o.autoDownload
  const a = o.attempt
  if (a && typeof a === 'object' && isVersion(a.version) && isVersion(a.from) && typeof a.at === 'number' && Number.isFinite(a.at) && a.at >= 0) {
    out.attempt = { version: a.version, from: a.from, at: a.at }
  }
  return out
}

/**
 * News of this launch from the install attempt recorded before the last quit (the caller then clears it):
 * { kind: 'updated', from, version } | { kind: 'install-failed', version } | null.
 */
function startupNotice(file, current, now) {
  const a = file && file.attempt
  if (!a || !isVersion(a.version) || !isVersion(current)) return null
  if (compareVersions(current, a.version) >= 0) return { kind: 'updated', from: a.from, version: current }
  if (current === a.from && now - a.at < INSTALL_NOTICE_MS) return { kind: 'install-failed', version: a.version }
  return null
}

/** One line of userData/logs/updater.log. */
function logLine(level, message, date) {
  const d = date instanceof Date ? date : new Date(typeof date === 'number' ? date : Date.now())
  const iso = Number.isFinite(d.getTime()) ? d.toISOString() : new Date(0).toISOString()
  const msg = String(message).replace(/\r\n|\r|\n/g, ' ⏎ ')
  return `${iso} [${level}] ${msg}`.slice(0, LOG_LINE_MAX)
}

module.exports = {
  RELEASES_URL,
  FEED,
  NOTES_MAX,
  ERROR_TEXT,
  isVersion,
  compareVersions,
  resolveProfileDir,
  appUserModelId,
  detectKind,
  mapUpdaterError,
  notesToText,
  normalizeInfo,
  initialState,
  reduceUpdateState,
  checkDue,
  parsePrefsArg,
  parseUpdaterFile,
  startupNotice,
  logLine,
}
