// Scenarios: a project kind + size, a fault level and weights over the action catalog. Several scenarios can be run
// together (their weights are added). Groups: A limits & data, B queue & network, C repeated loops, D monkey.
import type { ScenarioDef } from './types'

const SCENE_EDITS = { 'scene.prompt': 6, 'scene.title': 2, 'scene.settings': 2, 'scene.add': 2, 'scene.remove': 1, 'scene.duplicate': 1, 'scene.next': 1, 'scene.move': 2 }
const REF_EDITS = { 'refs.link': 5, 'refs.unlink': 4, 'refs.move': 4, 'refs.toScene': 2, 'refs.token': 3, 'refs.deleteWires': 2 }
const ASSET_EDITS = { 'asset.add': 2, 'asset.images': 4, 'asset.rename': 1, 'asset.remove': 1, 'asset.canvas': 1 }
const RUNS = { 'run.enqueue': 6, 'run.cancel': 2, 'run.retry': 2, 'run.wait': 4, 'run.star': 1, 'run.delete': 1 }
const FAULTS = { 'fault.preset': 2, 'fault.random': 3, 'fault.job': 2, 'fault.force': 1, 'fault.session': 1, 'fault.balance': 1, 'fault.clear': 2 }
const HISTORY = { 'history.undo': 3, 'history.redo': 3, 'history.roundTrip': 1 }

export const SCENARIOS: ScenarioDef[] = [
  // ---- A: limits & data ----
  {
    id: 'huge-project',
    label: 'Dự án khổng lồ',
    group: 'A',
    hint: 'Hàng nghìn cảnh, nhân vật và video; sửa, nối dây, hoàn tác trên dự án lớn.',
    minutes: 10,
    headless: true,
    app: true,
    tier: 'XL',
    faults: 'none',
    weights: { ...SCENE_EDITS, ...REF_EDITS, ...HISTORY, 'scene.layout': 2, 'scene.import': 1, 'persist.roundTrip': 1 },
    drainEvery: 0,
  },
  {
    id: 'long-prompts',
    label: 'Prompt quá dài / rỗng',
    group: 'A',
    hint: 'Prompt đúng bằng, vượt 1 ký tự, gấp 3 giới hạn; rỗng; chỉ khoảng trắng — rồi bấm Tạo video.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'scene.prompt': 10, 'scene.type': 3, 'scene.settings': 3, 'run.enqueue': 5, 'run.wait': 3, 'persist.roundTrip': 1 },
    drainEvery: 60,
  },
  {
    id: 'refs-over-cap',
    label: 'Vượt giới hạn ảnh tham chiếu',
    group: 'A',
    hint: 'Nối 10–45 nhân vật một lúc, đổi sang MiniMax-H3 (9 ảnh), thêm ảnh cho nhân vật — @image phải giữ đúng người.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'M',
    faults: 'none',
    weights: { 'refs.link': 8, 'refs.move': 4, 'refs.unlink': 3, 'asset.images': 5, 'scene.settings': 4, 'refs.token': 3, 'run.enqueue': 3, 'run.wait': 2 },
    drainEvery: 80,
  },
  {
    id: 'huge-media',
    label: 'Ảnh hỏng / sai định dạng / rất lớn',
    group: 'A',
    hint: 'Nhân vật có ảnh rỗng, GIF, file hỏng, ảnh nhiều MB, 40 ảnh — rồi tạo video.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'asset.add': 6, 'asset.images': 4, 'refs.link': 6, 'run.enqueue': 6, 'run.wait': 4, 'run.retry': 2 },
    drainEvery: 40,
  },
  {
    id: 'unicode-fuzz',
    label: 'Chữ lạ (NFD, emoji, RTL, ký tự điều khiển)',
    group: 'A',
    hint: 'Tên, prompt, tên file chứa tiếng Việt tổ hợp, emoji ZWJ, chữ Ả Rập, ký tự 0, tên dành riêng của Windows.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'scene.prompt': 5, 'scene.title': 4, 'asset.rename': 3, 'asset.add': 2, 'run.rename': 4, 'folder.add': 2, 'persist.parsers': 4, 'persist.roundTrip': 2, 'run.enqueue': 2, 'run.wait': 2 },
    drainEvery: 60,
  },
  {
    id: 'parser-fuzz',
    label: 'Bộ đọc dữ liệu (file hỏng)',
    group: 'A',
    hint: 'migrate với dữ liệu hỏng, bộ đọc prompt nhập hàng loạt, token, tên file — không bao giờ được ném lỗi.',
    minutes: 3,
    headless: true,
    app: false,
    tier: 'S',
    faults: 'none',
    weights: { 'persist.corrupt': 6, 'persist.parsers': 6, 'persist.roundTrip': 1, 'scene.prompt': 1 },
    drainEvery: 0,
  },
  {
    id: 'legacy-video',
    label: 'Dữ liệu cũ có video tham chiếu',
    group: 'A',
    hint: 'Dự án cũ còn @video_N, @video_?N, “Continue from @video_1:” — thao tác thường không được làm hỏng chữ.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'M',
    faults: 'none',
    project: 'legacy-video',
    weights: { ...REF_EDITS, ...SCENE_EDITS, ...HISTORY, 'run.delete': 1, 'persist.roundTrip': 2 },
    drainEvery: 0,
  },

  // ---- B: queue & network ----
  {
    id: 'queue-flood',
    label: 'Ngập hàng đợi',
    group: 'B',
    hint: 'Xếp hàng trăm video một lúc, huỷ / thử lại giữa chừng; tối đa 10 chạy cùng lúc, mỗi take một job.',
    minutes: 10,
    headless: true,
    app: true,
    tier: 'M',
    faults: 'none',
    project: 'bridge-full',
    weights: { 'run.enqueue': 8, 'run.cancel': 3, 'run.retry': 2, 'run.wait': 6, 'run.delete': 1 },
    drainEvery: 50,
  },
  {
    id: 'fault-storm',
    label: 'Bão lỗi mạng',
    group: 'B',
    hint: '409, 429, 5xx, mất câu trả lời, chậm 20 giây, hết phiên, hết credit — không trả tiền hai lần, hàng đợi phải chạy hết.',
    minutes: 10,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'storm',
    project: 'bridge-full',
    weights: { ...RUNS, ...FAULTS },
    drainEvery: 40,
  },
  {
    id: 'dedupe-off',
    label: 'Máy chủ không chống trùng',
    group: 'B',
    hint: 'canvasapp giả lập tạo job mới cho mỗi POST: SanoVids không được gửi lại một take đã có thể bị tính tiền.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'sometimes',
    project: 'bridge-full',
    server: { dedupe: false },
    weights: { 'run.enqueue': 6, 'run.wait': 6, 'run.retry': 3, 'fault.random': 4, 'fault.preset': 2, 'fault.clear': 2 },
    drainEvery: 30,
  },
  {
    id: 'run-cancel',
    label: 'Tạo rồi huỷ liên tục',
    group: 'B',
    hint: 'Bấm Tạo video rồi huỷ / xoá ngay, lặp lại — không job mồ côi, không take kẹt.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'sometimes',
    project: 'bridge-full',
    weights: { 'run.enqueue': 6, 'run.cancel': 6, 'run.delete': 3, 'run.retry': 2, 'run.wait': 3, 'fault.random': 1, 'fault.clear': 1 },
    drainEvery: 40,
  },

  // ---- C: repeated loops ----
  {
    id: 'link-unlink',
    label: 'Nối / cắt dây lặp lại',
    group: 'C',
    hint: 'Nối, cắt, đổi thứ tự, chuyển dây giữa các cảnh hàng nghìn lần — @image_N luôn đúng người.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { ...REF_EDITS, 'asset.images': 3, 'history.undo': 2, 'history.redo': 2 },
    drainEvery: 0,
  },
  {
    id: 'undo-soak',
    label: 'Hoàn tác sâu',
    group: 'C',
    hint: 'Hoàn tác / làm lại 250 bước, xen sửa — lịch sử ≤ 200 bước, làm lại phải y nguyên.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { ...HISTORY, 'history.roundTrip': 4, ...SCENE_EDITS, ...REF_EDITS, 'scene.type': 3 },
    drainEvery: 0,
  },
  {
    id: 'scene-churn',
    label: 'Thêm / xoá cảnh liên tục',
    group: 'C',
    hint: 'Thêm, nhập, nhân bản, xoá, đổi thứ tự cảnh — thứ tự S01… luôn liền mạch.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'scene.add': 4, 'scene.import': 2, 'scene.duplicate': 3, 'scene.next': 3, 'scene.remove': 5, 'scene.move': 4, 'history.undo': 2, 'history.redo': 1, 'scene.layout': 1 },
    drainEvery: 0,
  },
  {
    id: 'folder-loop',
    label: 'Thư mục lặp lại',
    group: 'C',
    hint: 'Thêm, nối, cắt, xoá node Thư mục (không bao giờ là thư mục thật) xen với xoá cảnh / video.',
    minutes: 5,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'folder.add': 3, 'folder.link': 5, 'folder.unlink': 4, 'folder.remove': 2, 'scene.remove': 1, 'run.delete': 1, 'history.undo': 2, 'history.redo': 2 },
    drainEvery: 0,
  },
  {
    id: 'rename-loop',
    label: 'Đổi tên lặp lại',
    group: 'C',
    hint: 'Đổi tên cảnh, nhân vật, file video bằng chữ lạ — tên file luôn an toàn.',
    minutes: 3,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'scene.title': 4, 'asset.rename': 4, 'run.rename': 6, 'persist.parsers': 2 },
    drainEvery: 0,
  },
  {
    id: 'typing-storm',
    label: 'Gõ phím liên tục',
    group: 'C',
    hint: 'Gõ, xoá, chèn @nhân vật vào prompt rất nhanh — gộp hoàn tác đúng, không mất chữ.',
    minutes: 3,
    headless: true,
    app: true,
    tier: 'S',
    faults: 'none',
    weights: { 'scene.type': 8, 'refs.token': 3, 'history.undo': 2, 'history.redo': 2, 'history.roundTrip': 1 },
    drainEvery: 0,
  },
  {
    id: 'ui-cycle',
    label: 'Đổi giao diện liên tục',
    group: 'C',
    hint: 'Đổi Canvas / Bảng / Storyboard, chọn hàng nghìn cảnh, mở / đóng bảng — giao diện không treo.',
    minutes: 3,
    headless: false,
    app: true,
    tier: 'L',
    faults: 'none',
    weights: { 'ui.view': 4, 'ui.select': 4, 'ui.panels': 4, 'scene.prompt': 1, 'refs.link': 1 },
    drainEvery: 0,
  },

  // ---- D: monkey ----
  {
    id: 'monkey',
    label: 'Khỉ nghịch (mọi thứ)',
    group: 'D',
    hint: 'Mọi thao tác ngẫu nhiên theo seed, có lỗi mạng — chạy lại đúng seed để tái hiện lỗi.',
    minutes: 15,
    headless: true,
    app: true,
    tier: 'M',
    faults: 'sometimes',
    weights: {
      ...SCENE_EDITS,
      ...REF_EDITS,
      ...ASSET_EDITS,
      ...HISTORY,
      ...RUNS,
      ...FAULTS,
      'scene.type': 2,
      'scene.layout': 1,
      'scene.frame': 1,
      'scene.preset': 1,
      'run.rename': 1,
      'folder.add': 1,
      'folder.link': 1,
      'folder.unlink': 1,
      'folder.remove': 1,
      'persist.roundTrip': 1,
      'persist.parsers': 1,
      'ui.view': 1,
      'ui.select': 1,
      'ui.panels': 1,
    },
    drainEvery: 100,
  },
]

export const SCENARIO_BY_ID = new Map(SCENARIOS.map((s) => [s.id, s]))

/** Scaling of the fault actions' weights by level ('none' removes them). */
export const FAULT_SCALE = { none: 0, sometimes: 1, storm: 4 } as const

/** Not implemented on purpose (documented in the report): need a second window / a full disk. */
export const NOT_IMPLEMENTED = [
  'Nhiều tab cùng mở một dự án (cần cửa sổ thứ hai).',
  'Bộ nhớ trình duyệt đầy (không giả lập được an toàn khi dự án thật đang mở).',
]
