// Custom edges: image references (asset -> scene), H3 first/last frames (asset -> scene),
// video references (take -> scene, @video_N) and take outputs (scene -> take, not deletable).
import { BaseEdge, EdgeLabelRenderer, getBezierPath, type Edge, type EdgeProps } from '@xyflow/react'
import { X } from 'lucide-react'
import { memo } from 'react'
import { parseEdgeId, takeLabel, type EdgeKind } from '../../actions'
import { undoToastAction, useProject } from '../../store/project'
import { toast, useUI } from '../../store/ui'
import { keepHover, scheduleHoverEnd, useCanvasLocal, withAlpha } from './canvasModel'

export type LinkEdgeData = {
  kind: EdgeKind
  /** Position of this wire among the wires arriving at the scene's left handle (spreads them at the target). */
  index: number
  count: number
  /** Asset color (ref / frame edges). */
  color: string
  /** Touches the hovered / selected node. */
  highlight: boolean
}
export type LinkEdge = Edge<LinkEdgeData>

/** Purple of video wires / handles (same value as the canvas-local CSS var --video). */
export const VIDEO_COLOR = '#b48cff'

const KIND_STROKE: Record<EdgeKind, string> = {
  ref: '#4fb6a8',
  first: '#4cc38a',
  last: '#b48cff',
  vref: VIDEO_COLOR,
  out: '#6d7179',
}

const CUT_LABEL: Record<EdgeKind, string> = {
  ref: 'tham chiếu ảnh',
  first: 'khung đầu',
  last: 'khung cuối',
  vref: 'video tham chiếu',
  out: '',
}

/** Cut one link (one undo step) and say so. 'out' wires (scene → its take) cannot be cut. */
export function cutEdge(id: string, silent = false) {
  const e = parseEdgeId(id)
  if (!e || e.kind === 'out') return
  const p = useProject.getState()
  if (e.kind === 'ref') p.removeRef(e.to, e.from)
  else if (e.kind === 'vref') p.removeVideoRef(e.to, e.from, 'video ' + takeLabel(e.from))
  else p.setFrame(e.to, e.kind, null)
  const ui = useUI.getState()
  if (ui.selectedEdgeIds.includes(id)) ui.setSelectedEdges(ui.selectedEdgeIds.filter((x) => x !== id))
  useCanvasLocal.getState().setHoveredEdge(null)
  if (!silent) toast(`Đã bỏ nối ${CUT_LABEL[e.kind]}.`, { action: undoToastAction() })
}

function LinkEdgeComponent({ id, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, data, selected }: EdgeProps<LinkEdge>) {
  const hovered = useCanvasLocal((s) => s.hoveredEdgeId === id)
  const kind = data?.kind ?? 'ref'
  let ty = targetY
  if ((kind === 'ref' || kind === 'vref') && data && data.count > 1) {
    const off = (data.index - (data.count - 1) / 2) * 6
    ty = targetY + Math.max(-48, Math.min(48, off))
  }
  const [path, labelX, labelY] = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY: ty, targetPosition, curvature: 0.3 })
  const hl = !!data?.highlight || hovered || !!selected
  const base = KIND_STROKE[kind]

  if (kind === 'out') {
    // Subtle: the take was generated by this scene. Not selectable, not deletable.
    return (
      <BaseEdge
        id={id}
        path={path}
        interactionWidth={0}
        style={{ stroke: hl ? '#8d93a0' : base, strokeWidth: hl ? 1.8 : 1.2, strokeDasharray: '3 4', opacity: hl ? 0.95 : 0.55 }}
      />
    )
  }

  const stroke = kind === 'ref' && hl && data?.color ? withAlpha(data.color, 0.7) : base
  const style = {
    stroke,
    strokeWidth: selected ? 3 : hl ? 2.2 : kind === 'vref' ? 1.8 : 1.5,
    opacity: hl ? 1 : kind === 'vref' ? 0.75 : 0.45,
    filter: selected ? `drop-shadow(0 0 4px ${withAlpha(kind === 'ref' ? (data?.color ?? base) : base, 0.7)})` : undefined,
  }
  return (
    <>
      <BaseEdge id={id} path={path} style={style} interactionWidth={18} />
      {(hovered || selected) && (
        <EdgeLabelRenderer>
          <button
            className="cv-edge-cut nodrag nopan"
            style={{ transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)` }}
            title="Bỏ nối (Delete)"
            aria-label="Bỏ nối"
            onMouseEnter={() => {
              keepHover()
              useCanvasLocal.getState().setHoveredEdge(id)
            }}
            onMouseLeave={() => scheduleHoverEnd(() => useUI.getState().setHovered(null), 180)}
            onClick={(e) => {
              e.stopPropagation()
              cutEdge(id)
            }}
          >
            <X size={12} strokeWidth={2.6} />
          </button>
        </EdgeLabelRenderer>
      )}
    </>
  )
}

export const LinkEdgeView = memo(LinkEdgeComponent)

export const edgeTypes = {
  ref: LinkEdgeView,
  first: LinkEdgeView,
  last: LinkEdgeView,
  vref: LinkEdgeView,
  out: LinkEdgeView,
}
