// High-level commands shared by toolbar buttons, keyboard shortcuts, context menus and panels.
// Keep UI components thin: they call these, these call the stores.
import { compileScene, sceneCode, takeCode, tokenForAsset } from './core/compile'
import { checkTakeDelete, keyboardDeletePlan, type TakeDeleteConfirm } from './core/deletePlan'
import { usesVideoRefs } from './core/models'
import { restoredFromTake } from './components/runs/restore'
import type { AssetKind, XY } from './core/types'
import { prepareFolderAccess, saveFiles, savePendingDownloads, takeFiles, useDownloadPrefs, type FileToSave, type SaveResult } from './lib/downloads'
import { deleteMedia, getBlob, putBlob } from './lib/imageStore'
import { redo, setTakeHeightSource, undo, undoToastAction, useProject } from './store/project'
import { useRuns } from './store/runs'
import { toast, useUI } from './store/ui'

// Scene rows on the canvas grow with their tallest (resized) take: the project store's layout asks the runs store.
setTakeHeightSource((sceneId) => {
  let h = 0
  for (const t of useRuns.getState().takes) if (t.sceneId === sceneId && t.size && t.size.h > h) h = t.size.h
  return h
})

// ---------------- edge ids ----------------
/**
 * ref   asset → scene   (reference image, @image_N)
 * first / last  asset → scene (H3 transform frames)
 * out   scene → take    (the take was generated by the scene; not deletable)
 * vref  take  → scene   (reference video, @video_N)
 */
export type EdgeKind = 'ref' | 'first' | 'last' | 'out' | 'vref'
export const edgeId = (kind: EdgeKind, from: string, to: string) => `${kind}:${from}->${to}`
export function parseEdgeId(id: string): { kind: EdgeKind; from: string; to: string } | null {
  const m = /^(ref|first|last|out|vref):(.+)->(.+)$/.exec(id)
  return m ? { kind: m[1] as EdgeKind, from: m[2], to: m[3] } : null
}

// ---------------- canvas event bus (canvas listens; others request) ----------------
export const canvasEvents = new EventTarget()
/** Canvas event that always fits (zooms) to the given ids, or to everything when empty. */
export const FIT_EVENT = 'fit'
export function fitNodes(ids: string[] = []) {
  canvasEvents.dispatchEvent(new CustomEvent(FIT_EVENT, { detail: ids }))
}
/** Ask the canvas to pan to these node ids if they are off-screen (all nodes when empty). */
export function focusNodes(ids: string[] = []) {
  canvasEvents.dispatchEvent(new CustomEvent('focus', { detail: ids }))
}

// ---------------- selection helpers ----------------
export function selectedSceneIds(): string[] {
  const { selectedIds } = useUI.getState()
  const scenes = new Set(useProject.getState().project.scenes.map((s) => s.id))
  return selectedIds.filter((id) => scenes.has(id))
}

/**
 * Assets to connect: the ones selected ON THE CANVAS when there are any; otherwise the library selection.
 * Never both — a library selection made earlier is easy to forget and would silently link extra images.
 */
export function selectedAssetIds(): string[] {
  const { selectedIds, librarySelection } = useUI.getState()
  return pickAssetSelection(selectedIds, librarySelection, new Set(useProject.getState().project.assets.map((a) => a.id)))
}

/** Pure rule behind selectedAssetIds (unit-tested). */
export function pickAssetSelection(canvasSelection: string[], librarySelection: string[], assetIds: Set<string>): string[] {
  const onCanvas = canvasSelection.filter((id) => assetIds.has(id))
  if (onCanvas.length) return [...new Set(onCanvas)]
  return [...new Set(librarySelection.filter((id) => assetIds.has(id)))]
}

/** Take (video) nodes selected on the canvas. */
export function selectedTakeIds(): string[] {
  const { selectedIds } = useUI.getState()
  const takes = new Set(useRuns.getState().takes.map((t) => t.id))
  return selectedIds.filter((id) => takes.has(id))
}

/** "S03·T2" — short label of a take (toasts, file names). Tokens that lose their video become `videoLabel(id)`. */
export function takeLabel(takeId: string): string {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return 'video'
  const scene = useProject.getState().project.scenes.find((s) => s.id === take.sceneId)
  return takeCode(scene?.order, take.number)
}

// ---------------- connecting ----------------
/** Link assets (reference images) to scenes in one undo step and report what happened. */
export function linkAssets(sceneIds: string[], assetIds: string[]) {
  if (!sceneIds.length || !assetIds.length) return
  const res = useProject.getState().addRefs(sceneIds, assetIds)
  const names = assetIds.map((id) => useProject.getState().project.assets.find((a) => a.id === id)?.name).filter(Boolean)
  if (res.added) {
    toast(
      `Đã nối ${names.slice(0, 3).join(', ')}${names.length > 3 ? ` +${names.length - 3}` : ''} → ${res.scenes} cảnh${res.skipped ? ` (bỏ qua ${res.skipped} vì vượt giới hạn ảnh)` : ''}`,
      { tone: 'success', action: undoToastAction() },
    )
  } else if (res.skipped) {
    toast(`Không nối được: vượt giới hạn ảnh của model (${res.skipped}).`, { tone: 'warning' })
  } else {
    toast('Các cảnh đã có sẵn những tham chiếu này.', { tone: 'info' })
  }
}

/** Link takes (reference videos, @video_N) to scenes. Only completed takes can be used. */
export function linkTakes(sceneIds: string[], takeIds: string[]) {
  if (!sceneIds.length || !takeIds.length) return
  const takes = useRuns.getState().takes
  const ready = takeIds.filter((id) => takes.find((t) => t.id === id)?.status === 'completed')
  // A scene cannot reference its own takes (that would be a loop in the story).
  const ownScene = new Map(takes.map((t) => [t.id, t.sceneId]))
  if (!ready.length) {
    toast('Video chưa tạo xong nên chưa dùng làm tham chiếu được.', { tone: 'warning' })
    return
  }
  const targets = sceneIds.filter((sid) => ready.some((t) => ownScene.get(t) !== sid))
  if (!targets.length) {
    toast('Không thể dùng video của chính cảnh này làm tham chiếu cho nó.', { tone: 'warning' })
    return
  }
  // Per pair: a scene never gets one of its own takes, even when several scenes and takes are linked at once.
  const res = useProject.getState().addVideoRefs(targets, ready, (sid, t) => ownScene.get(t) === sid)
  if (res.added) {
    toast(`Đã nối ${ready.map(takeLabel).join(', ')} làm video tham chiếu → ${res.scenes} cảnh${res.skipped ? ` (bỏ qua ${res.skipped})` : ''}`, {
      tone: 'success',
      action: undoToastAction(),
    })
  } else if (res.skipped) {
    toast('Không nối được: model/chế độ của cảnh không nhận thêm video tham chiếu.', { tone: 'warning' })
  } else {
    toast('Các cảnh đã có sẵn video này.', { tone: 'info' })
  }
}

/** "C" — connect every selected asset/take to every selected scene (matrix connect). */
export function connectSelection() {
  const scenes = selectedSceneIds()
  const assets = selectedAssetIds()
  const takes = selectedTakeIds()
  if (!scenes.length || (!assets.length && !takes.length)) {
    toast('Chọn ít nhất 1 nhân vật/bối cảnh hoặc 1 video, và 1 cảnh, rồi bấm C.', { tone: 'warning' })
    return
  }
  if (assets.length) linkAssets(scenes, assets)
  if (takes.length) linkTakes(scenes, takes)
}

/**
 * For the prompt editor: make sure `assetId` is linked to the scene and return its "@image_N" token.
 * Returns null when it cannot be linked (image limit).
 */
export function ensureAssetToken(sceneId: string, assetId: string): string | null {
  const state = useProject.getState()
  let scene = state.project.scenes.find((s) => s.id === sceneId)
  if (!scene) return null
  if (!scene.refs.includes(assetId)) {
    const res = state.addRefs([sceneId], [assetId])
    if (!res.added) {
      toast('Không nối được: vượt giới hạn ảnh của model.', { tone: 'warning' })
      return null
    }
    scene = useProject.getState().project.scenes.find((s) => s.id === sceneId)!
  }
  return tokenForAsset(useProject.getState().project, scene, assetId)
}

// ---------------- create / delete / duplicate ----------------
export function newScene(position?: XY) {
  const id = useProject.getState().addScene({}, position ? { position } : {})
  useUI.getState().select([id])
  focusNodes([id])
  return id
}

/** "N" — create the next scene after the (last) selected scene, inheriting its references and settings. */
export function nextScene(position?: XY) {
  const sel = selectedSceneIds()
  const project = useProject.getState().project
  const from = sel.length ? project.scenes.filter((s) => sel.includes(s.id)).sort((a, b) => b.order - a.order)[0] : undefined
  if (!from) return newScene(position)
  const id = useProject.getState().createNextScene(from.id, position)
  useUI.getState().select([id])
  focusNodes([id])
  toast(`Đã tạo cảnh tiếp theo sau ${sceneCode(from.order)} (giữ ảnh/video tham chiếu và cấu hình).`, { tone: 'success', action: undoToastAction() })
  return id
}

/**
 * New scene that continues from a finished take: same references as the take's scene, the take as @video_1
 * and a prompt starter. Placed below the source scene (or at `position`).
 */
export function createSceneFromTake(takeId: string, position?: XY) {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return null
  if (take.status !== 'completed') {
    toast('Video chưa tạo xong.', { tone: 'warning' })
    return null
  }
  const project = useProject.getState().project
  const source = project.scenes.find((s) => s.id === take.sceneId)
  if (!source) {
    toast('Cảnh gốc của video này đã bị xoá.', { tone: 'warning' })
    return null
  }
  if (!usesVideoRefs(source.settings)) {
    toast('Chế độ của cảnh gốc không nhận video tham chiếu. Đổi model/chế độ (ví dụ Seedance 2.5) rồi thử lại.', { tone: 'warning' })
    return null
  }
  const id = useProject.getState().createNextScene(source.id, position, { videoRefs: [takeId], prompt: 'Continue from @video_1: ' })
  useUI.getState().select([id])
  focusNodes([id])
  toast(`Đã tạo cảnh tiếp nối từ ${takeLabel(takeId)} (@video_1).`, { tone: 'success', action: undoToastAction() })
  return id
}

export function duplicateSelection() {
  const ids = selectedSceneIds()
  if (!ids.length) return
  const created = useProject.getState().duplicateScenes(ids)
  useUI.getState().select(created)
  toast(`Đã nhân bản ${created.length} cảnh.`, { tone: 'success', action: undoToastAction() })
}

export { keyboardDeletePlan, checkTakeDelete, type TakeDeleteConfirm } from './core/deletePlan'

/**
 * Delete what is selected: cut selected wires, delete scenes, hide asset nodes from the canvas (one undo step),
 * and delete selected takes for good (after confirmation when a finished video would be lost or is used as @video;
 * takes are not undoable). Takes selected together with their own scene are spared (keyboardDeletePlan): deleting
 * the scene hides them and Undo brings them back.
 */
export function deleteSelection() {
  const { selectedIds, selectedEdgeIds } = useUI.getState()
  const project = useProject.getState().project
  const takes = useRuns.getState().takes
  const sceneById = new Map(project.scenes.map((s) => [s.id, s]))
  const assetSet = new Set(project.assets.map((a) => a.id))

  const sceneIds = selectedIds.filter((id) => sceneById.has(id))
  const hideAssetIds = selectedIds.filter((id) => assetSet.has(id))
  const plan = keyboardDeletePlan(selectedIds, new Set(sceneById.keys()), new Map(takes.map((t) => [t.id, t.sceneId])))
  const takeIds = plan.takes
  const deadScenes = new Set(sceneIds)

  const refs: { sceneId: string; assetId: string }[] = []
  const videoRefs: { sceneId: string; takeId: string }[] = []
  const frames: { sceneId: string; which: 'first' | 'last' }[] = []
  for (const id of selectedEdgeIds) {
    const e = parseEdgeId(id)
    if (!e) continue
    const scene = sceneById.get(e.to)
    // Skip wires that no longer exist or whose scene is being deleted anyway.
    if (!scene || deadScenes.has(scene.id)) continue
    if (e.kind === 'ref' && scene.refs.includes(e.from)) refs.push({ sceneId: e.to, assetId: e.from })
    else if (e.kind === 'vref' && scene.videoRefs.includes(e.from)) videoRefs.push({ sceneId: e.to, takeId: e.from })
    else if (e.kind === 'first' && scene.firstFrame === e.from) frames.push({ sceneId: e.to, which: 'first' })
    else if (e.kind === 'last' && scene.lastFrame === e.from) frames.push({ sceneId: e.to, which: 'last' })
  }

  const links = refs.length + videoRefs.length + frames.length
  // Ask BEFORE changing anything: Cancel must leave the whole selection untouched.
  if (takeIds.length) {
    const check = checkTakeDelete(takeIds, takes, project.scenes, { ignoreScenes: deadScenes, label: takeIds.length === 1 ? takeLabel(takeIds[0]) : undefined })
    if (check.question && !window.confirm(check.question)) return
  }
  // Takes first: their labels ("video S01·T1") need their scene, which deleteItems may remove.
  const takesDeleted = takeIds.length ? (deleteTakes(takeIds, { confirm: false, toast: false }) ?? 0) : 0
  if (sceneIds.length || hideAssetIds.length || links) {
    useProject.getState().deleteItems({ sceneIds, hideAssetIds, refs, videoRefs, frames }, videoLabel)
  }
  if (!sceneIds.length && !hideAssetIds.length && !links && !takesDeleted) return
  useUI.getState().clearSelection()
  const deleted = [sceneIds.length && `${sceneIds.length} cảnh`, takesDeleted && `${takesDeleted} video`, links && `${links} dây nối`].filter(Boolean)
  const said = [deleted.length && `Đã xoá ${deleted.join(', ')}`, hideAssetIds.length && `${deleted.length ? 'đã ẩn' : 'Đã ẩn'} ${hideAssetIds.length} thẻ khỏi canvas`]
  const undoable = sceneIds.length || hideAssetIds.length || links
  toast(`${said.filter(Boolean).join('; ')}.${takesDeleted ? ' ' + TAKES_GONE_NOTE : ''}`, undoable ? { action: undoToastAction() } : {})
}

/** Appended to every toast about deleted takes. */
export const TAKES_GONE_NOTE = '(Video đã xoá không hoàn tác được.)'

export interface DeleteTakesOptions {
  /**
   * Ask first (window.confirm). true (default) = when a finished video would be lost or a scene uses one as @video;
   * 'usedOnly' = only for @video users (the caller already confirmed, e.g. a two-click button); false = never.
   */
  confirm?: TakeDeleteConfirm
  /** Show the result toast (default true). */
  toast?: boolean
  /** Scenes deleted in the same operation: their @video uses are not mentioned in the question. */
  ignoreScenes?: ReadonlySet<string>
}

/**
 * The one way to delete takes for good (canvas node, take viewer, queue, Delete key): asks when needed, cancels
 * running jobs, removes the takes (and drops them from every scene's @video references, renumbering prompts),
 * deletes their poster/video files (nothing can bring a deleted take back, so its media would only fill the
 * browser's quota), drops them from the selection and says so in a toast.
 * Returns how many takes were deleted, or null when the user cancelled the question.
 */
export function deleteTakes(takeIds: readonly string[], opts: DeleteTakesOptions = {}): number | null {
  const project = useProject.getState().project
  const all = useRuns.getState().takes
  const check = checkTakeDelete(takeIds, all, project.scenes, {
    confirm: opts.confirm ?? true,
    ignoreScenes: opts.ignoreScenes,
    label: takeIds.length === 1 ? takeLabel(takeIds[0]) : undefined,
  })
  if (!check.ids.length) return 0
  if (check.question && !window.confirm(check.question)) return null
  // Labels before the takes are gone.
  const label = check.ids.length === 1 ? takeLabel(check.ids[0]) : `${check.ids.length} video`
  const usedCodes = check.usedBy.map((s) => sceneCode(s.order))
  const ids = new Set(check.ids)
  const dead = all.filter((t) => ids.has(t.id))
  useRuns.getState().removeTakes(check.ids)
  for (const t of dead) {
    if (t.posterId) void deleteMedia(t.posterId).catch(() => undefined)
    if (t.videoId) void deleteMedia(t.videoId).catch(() => undefined)
  }
  const ui = useUI.getState()
  if (ui.selectedIds.some((id) => ids.has(id))) ui.select(ui.selectedIds.filter((id) => !ids.has(id)))
  if (opts.toast ?? true) toast(`Đã xoá ${label}${usedCodes.length ? ` và bỏ @video ở ${usedCodes.join(', ')}` : ''}. ${TAKES_GONE_NOTE}`)
  return dead.length
}

/**
 * Delete takes for good without asking and without a toast.
 * @deprecated use `deleteTakes(ids, { confirm, toast })`.
 */
export function deleteTakesForever(takeIds: string[]): number {
  return deleteTakes(takeIds, { confirm: false, toast: false }) ?? 0
}

// ---------------- assets from files ----------------
export async function createAssetsFromFiles(files: File[], opts: { kind?: AssetKind; position?: XY | null } = {}): Promise<string[]> {
  const images = files.filter((f) => /^image\//.test(f.type))
  if (!images.length) {
    toast('Chỉ nhận file ảnh (JPG, PNG, WEBP).', { tone: 'warning' })
    return []
  }
  const ids: string[] = []
  let i = 0
  for (const file of images) {
    const imageId = await putBlob(file, 'img')
    const name = file.name.replace(/\.[^.]+$/, '').replace(/[_-]+/g, ' ').trim().slice(0, 40) || 'Ảnh'
    const position = opts.position ? { x: opts.position.x + i * 24, y: opts.position.y + i * 24 } : (opts.position ?? null)
    ids.push(useProject.getState().addAsset({ name, kind: opts.kind ?? 'character', imageIds: [imageId], position }))
    i++
  }
  toast(`Đã thêm ${ids.length} mục vào thư viện.`, { tone: 'success' })
  return ids
}

export async function addImagesToAsset(assetId: string, files: File[]) {
  if (!useProject.getState().project.assets.some((a) => a.id === assetId)) return
  const ids: string[] = []
  for (const f of files.filter((f) => /^image\//.test(f.type))) ids.push(await putBlob(f, 'img'))
  if (!ids.length) return
  // Storing takes a while: append to the images the asset has NOW (the user may have removed, reordered or added
  // images meanwhile), not to the list read before the writes.
  const current = useProject.getState().project.assets.find((a) => a.id === assetId)
  if (!current) {
    for (const id of ids) void deleteMedia(id).catch(() => undefined)
    return
  }
  useProject.getState().updateAsset(assetId, { imageIds: [...current.imageIds, ...ids] })
}

// ---------------- running ----------------
/** Open the run confirmation dialog (cost summary) for scenes. Defaults to the selection. */
export function requestRun(sceneIds: string[] = selectedSceneIds()) {
  if (!sceneIds.length) {
    toast('Chọn cảnh cần chạy trước.', { tone: 'warning' })
    return
  }
  useUI.getState().openDialog({ kind: 'runConfirm', sceneIds })
}

/** Enqueue immediately (used by the confirm dialog). */
export function runNow(sceneIds: string[]) {
  const res = useRuns.getState().enqueue(sceneIds)
  if (res.error) {
    toast(res.error, { tone: 'error' })
    return res
  }
  toast(`Đã gửi ${res.queued} cảnh vào hàng đợi · −${res.cost} credit${res.skipped.length ? ` · bỏ qua ${res.skipped.length}` : ''}`, { tone: 'success' })
  return res
}

export function restoreFromTake(takeId: string) {
  const runs = useRuns.getState()
  const take = runs.takes.find((t) => t.id === takeId)
  if (!take) return
  const project = useProject.getState().project
  if (!project.scenes.some((s) => s.id === take.sceneId)) {
    toast('Cảnh của take này đã bị xoá.', { tone: 'warning' })
    return
  }
  const live = new Set(runs.takes.map((t) => t.id))
  // Tokens of references that no longer exist are renumbered / replaced, like removing a reference by hand.
  const r = restoredFromTake(take, project.assets, live, { renumber: project.settings.autoRenumber, videoLabel })
  // One store mutation = one undo step, so the toast's "Hoàn tác" reverts everything together.
  useProject.getState().restoreScene(take.sceneId, { prompt: r.prompt, refs: r.refs, videoRefs: r.videoRefs, settings: take.settings }, live)
  const extra = r.gone ? ` (bỏ ${r.gone} tham chiếu không còn tồn tại${r.renumbered ? ', đã đánh lại số @image/@video' : ''})` : ''
  toast(`Đã khôi phục prompt & tham chiếu của T${take.number}${extra}.`, {
    tone: 'success',
    action: undoToastAction(),
  })
}

// ---------------- copy / export ----------------
function compiledFor(sceneId: string) {
  const project = useProject.getState().project
  const scene = project.scenes.find((s) => s.id === sceneId)
  if (!scene) return null
  const takes = useRuns.getState().takes
  return { project, scene, compiled: compileScene(project, scene, { takeStatus: (id) => takes.find((t) => t.id === id)?.status }) }
}

export async function copyCompiledPrompt(sceneId: string) {
  const c = compiledFor(sceneId)
  if (!c) return
  try {
    await navigator.clipboard.writeText(c.compiled.text)
    toast(`Đã copy prompt ${sceneCode(c.scene.order)} (${c.compiled.charCount.toLocaleString('vi-VN')} ký tự).`, { tone: 'success' })
  } catch {
    toast('Trình duyệt chặn clipboard. Hãy copy thủ công trong ô xem trước.', { tone: 'error' })
  }
}

/** Zip with the reference images/videos named in token order (image_01_Elara.png, video_01_S03-T2.webm) + prompt.txt. */
export async function downloadSceneZip(sceneId: string) {
  const c = compiledFor(sceneId)
  if (!c) return
  const { project, scene, compiled } = c
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()
  zip.file('prompt.txt', compiled.text)
  for (const img of compiled.images) {
    const blob = await getBlob(img.imageId)
    if (!blob) continue
    const asset = project.assets.find((a) => a.id === img.assetId)
    const ext = blob.type.includes('png') ? 'png' : blob.type.includes('webp') ? 'webp' : blob.type.includes('svg') ? 'svg' : 'jpg'
    zip.file(`image_${String(img.n).padStart(2, '0')}_${asset?.tag ?? 'image'}.${ext}`, blob)
  }
  const takes = useRuns.getState().takes
  for (const v of compiled.videos) {
    const take = takes.find((t) => t.id === v.takeId)
    const blob = take?.videoId ? await getBlob(take.videoId) : null
    if (!blob) continue
    zip.file(`video_${String(v.n).padStart(2, '0')}_${takeLabel(v.takeId).replace('·', '-')}.webm`, blob)
  }
  const out = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(out)
  const a = document.createElement('a')
  a.href = url
  a.download = `${sceneCode(scene.order)}${scene.title ? '_' + scene.title.replace(/[<>:"/\\|?*]/g, '-') : ''}.zip`
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 10000)
}

/** Text a @video_N token becomes when its video is removed from a scene. */
export const videoLabel = (takeId: string) => (useRuns.getState().takes.some((t) => t.id === takeId) ? 'video ' + takeLabel(takeId) : 'video')

// ---------------- downloading videos ----------------
/** "S03_T2 - Ánh sáng trong hang" */
export function takeFileBase(takeId: string): string {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return 'video'
  const scene = useProject.getState().project.scenes.find((s) => s.id === take.sceneId)
  const code = `${scene ? sceneCode(scene.order) : 'S00'}_T${take.number}`
  return scene?.title ? `${code} - ${scene.title}` : code
}

/** One-click download of a finished take: the video (+ a .txt with the prompt that was sent). */
export async function downloadTake(takeId: string, opts: { auto?: boolean } = {}) {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take || take.status !== 'completed') {
    if (!opts.auto) toast('Video chưa tạo xong.', { tone: 'warning' })
    return false
  }
  const files = await takeFiles(take, takeFileBase(takeId), useDownloadPrefs.getState().withPrompt)
  if (!files.length) {
    if (!opts.auto) toast('Không tìm thấy file video của take này.', { tone: 'error' })
    return false
  }
  try {
    const res = await saveFiles(files, !opts.auto)
    reportSaved(res, `${takeLabel(takeId)}${files.length > 1 ? ' + prompt' : ''}`, files[0].name)
    return res.to !== 'pending'
  } catch (e) {
    toast(`Không lưu được video: ${(e as Error).message}`, { tone: 'error' })
    return false
  }
}

/** Toast for a finished save: where the files went, and what to do when the chosen folder could not be used. */
function reportSaved(res: SaveResult, what: string, firstName: string) {
  const renamed = res.to === 'folder' && res.names[0] && res.names[0] !== firstName ? ` (tên “${res.names[0]}” vì đã có file trùng tên)` : ''
  const extra = res.alsoSaved ? ` và ${res.alsoSaved} file đang chờ` : ''
  if (res.to === 'folder') toast(`Đã lưu ${what}${extra} vào thư mục “${res.folder}”${renamed}.`, { tone: 'success' })
  else if (res.to === 'pending')
    toast(`${what} đang chờ lưu vào “${res.folder}”: trình duyệt cần bạn cho phép ghi vào thư mục này lần nữa.`, {
      tone: 'warning',
      ms: 20000,
      action: { label: 'Cho phép & lưu', run: () => void savePendingNow() },
    })
  else if (res.reason === 'missing-folder')
    toast(`Không tìm thấy thư mục “${res.folder}” (đã đổi tên hoặc xoá?) nên đã tải ${what} về thư mục Downloads. Chọn lại thư mục trong Cài đặt.`, {
      tone: 'warning',
      ms: 8000,
    })
  else if (res.reason === 'no-permission')
    toast(`Chưa có quyền ghi vào “${res.folder}” nên đã tải ${what} về thư mục Downloads.`, { tone: 'warning', ms: 8000 })
  else toast(`Đã tải ${what} về máy.`, { tone: 'success' })
}

/** Toast button (a click, so the browser may ask for the folder permission): save the auto-downloads that wait. */
async function savePendingNow() {
  try {
    const res = await savePendingDownloads()
    if (!res) return
    if (res.to === 'folder') toast(`Đã lưu ${res.names.length} file vào thư mục “${res.folder}”.`, { tone: 'success' })
    else toast(`Chưa được phép ghi vào thư mục nên đã tải ${res.names.length} file về Downloads.`, { tone: 'warning' })
  } catch (e) {
    toast(`Không lưu được: ${(e as Error).message}`, { tone: 'error' })
  }
}

/** The chosen take of every scene (starred, else the latest completed), in scene order. */
export function chosenTakeIds(): string[] {
  const takes = useRuns.getState().takes
  const scenes = [...useProject.getState().project.scenes].sort((a, b) => a.order - b.order)
  const out: string[] = []
  for (const s of scenes) {
    const own = takes.filter((t) => t.sceneId === s.id && t.status === 'completed')
    const pick = own.find((t) => t.starred) ?? own.sort((a, b) => b.number - a.number)[0]
    if (pick) out.push(pick.id)
  }
  return out
}

/** Zip of the chosen take of every scene (S01_T2 - title.webm …) + prompts.txt. */
export async function downloadChosenTakesZip() {
  const ids = chosenTakeIds()
  if (!ids.length) {
    toast('Chưa có video nào tạo xong.', { tone: 'warning' })
    return
  }
  // Ask for the folder permission now, while the click still counts as a user gesture (zipping takes a while).
  await prepareFolderAccess()
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()
  const prompts: string[] = []
  for (const id of ids) {
    const take = useRuns.getState().takes.find((t) => t.id === id)!
    const base = takeFileBase(id)
    for (const f of await takeFiles(take, base, false)) zip.file(f.name, f.data)
    prompts.push(`=== ${base} ===\n${take.promptSnapshot}`)
  }
  zip.file('prompts.txt', prompts.join('\n\n'))
  const blob = await zip.generateAsync({ type: 'blob' })
  const name = `${useProject.getState().project.name.replace(/[<>:"/\\|?*]/g, '-')} - video chọn.zip`
  const file: FileToSave = { name, data: blob }
  const res = await saveFiles([file], true)
  reportSaved(res, `${ids.length} video (.zip)`, name)
}

/** Open the full-screen image viewer (whole picture, real aspect ratio). */
export function viewImages(imageIds: string[], index = 0, title?: string) {
  const ids = imageIds.filter(Boolean)
  if (!ids.length) return
  useUI.getState().openDialog({ kind: 'image', imageIds: ids, index, title })
}

/** Viewer for all images of a library asset. */
export function viewAssetImages(assetId: string, index = 0) {
  const asset = useProject.getState().project.assets.find((a) => a.id === assetId)
  if (asset) viewImages(asset.imageIds, index, asset.name)
}

export { undo, redo }
