// High-level commands shared by toolbar buttons, keyboard shortcuts, context menus and panels.
// Keep UI components thin: they call these, these call the stores.
import { compileScene, sceneCode, takeCode, tokenForAsset } from './core/compile'
import { checkTakeDelete, keyboardDeletePlan, type TakeDeleteConfirm } from './core/deletePlan'
import { refVideosProblem } from './core/runGate'
import { staleNoteSince } from './core/staleTokens'
import { MODELS, usesVideoRefs } from './core/models'
import { nameDate, nameTime, renderNameTemplate, type NameValues } from './core/nameTemplate'
import { chargedDemo, creditKindOf, formatCredits } from './lib/credits'
import { activeProviderId, getProvider, providerOf } from './providers'
import { cancelQuestion, cancelToastText, type CancelFacts } from './components/runs/creditText'
import { restoredFromTake } from './components/runs/restore'
import { cleanTakeFileName, uniqueInSet } from './core/fileNames'
import type { FolderLinkKind } from './core/folders'
import type { AssetKind, XY } from './core/types'
import {
  prepareFolderAccess,
  prepareSaveAs,
  runSaveAs,
  saveFiles,
  saveFilesAs,
  savePendingDownloads,
  takeFiles,
  useDownloadPrefs,
  type FileToSave,
  type SaveAsResult,
  type SaveResult,
} from './lib/downloads'
import { deleteMedia, getBlob, putBlob } from './lib/imageStore'
import { freeSpotFrom, LAYOUT, redo, setTakeLayoutSource, undo, undoToastAction, useProject, type Box, type PlaceHint } from './store/project'
import { isUncertainSubmit, remoteVideoReady, useRuns } from './store/runs'
import { currentTakeRows, takeLayoutSource } from './store/takeRows'
import { toast, useUI, type DevPanelTab, type TopUpTab } from './store/ui'

// Scene rows on the canvas grow with their tallest (resized) take, and new nodes step over take rows and videos placed
// by hand: the project store's layout asks the runs store (only takes shown in a row count for that row).
setTakeLayoutSource(takeLayoutSource)

// ---------------- where the user is working (placement of new nodes) ----------------
/** Scene selected most recently (kept after the selection is cleared): a new scene goes below it. */
let recentSceneId: string | null = null
/** Remember (or forget, null) the scene the user worked on last. Selecting a scene does it. */
export function noteRecentScene(id: string | null) {
  recentSceneId = id
}
useUI.subscribe((s, prev) => {
  if (s.selectedIds === prev.selectedIds || !s.selectedIds.length) return
  const scenes = useProject.getState().project.scenes
  for (let i = s.selectedIds.length - 1; i >= 0; i--) {
    const id = s.selectedIds[i]
    if (scenes.some((sc) => sc.id === id)) {
      recentSceneId = id
      return
    }
  }
})

/** Visible area of the canvas in flow coordinates (registered by CanvasView while it is shown). */
let canvasViewSource: (() => Box | null) | null = null
export function setCanvasViewSource(fn: () => Box | null): () => void {
  canvasViewSource = fn
  return () => {
    if (canvasViewSource === fn) canvasViewSource = null
  }
}

/** Where a new scene should go: below the scene worked on last, within what the canvas shows (project.newScenePosition). */
export function placementHint(): PlaceHint {
  const view = useUI.getState().view === 'canvas' ? (canvasViewSource?.() ?? null) : null
  return { anchorId: recentSceneId, view }
}

// ---------------- edge ids ----------------
/**
 * ref   asset → scene   (reference image, @image_N)
 * first / last  asset → scene (H3 transform frames)
 * out   scene → take    (the take was generated by the scene; not deletable)
 * vref  take  → scene   (reference video, @video_N)
 * save      take  → folder node (that video is copied into the folder)
 * autosave  scene → folder node (every new finished take of the scene is copied into the folder)
 */
export type EdgeKind = 'ref' | 'first' | 'last' | 'out' | 'vref' | FolderLinkKind
export const edgeId = (kind: EdgeKind, from: string, to: string) => `${kind}:${from}->${to}`
export function parseEdgeId(id: string): { kind: EdgeKind; from: string; to: string } | null {
  const m = /^(ref|first|last|out|vref|save|autosave):(.+)->(.+)$/.exec(id)
  return m ? { kind: m[1] as EdgeKind, from: m[2], to: m[3] } : null
}
/** Wires that end at a folder node. */
export const isFolderEdge = (kind: EdgeKind): kind is FolderLinkKind => kind === 'save' || kind === 'autosave'

// ---------------- canvas event bus (canvas listens; others request) ----------------
export const canvasEvents = new EventTarget()
/** Canvas event that always fits (zooms) to the given ids, or to everything when empty. */
export const FIT_EVENT = 'fit'
export function fitNodes(ids: string[] = []) {
  canvasEvents.dispatchEvent(new CustomEvent(FIT_EVENT, { detail: ids }))
}
/** Ask the canvas to go to these node ids if they are off-screen ("Đi tới": centred, zoomed in to a readable size). */
export function focusNodes(ids: string[] = []) {
  canvasEvents.dispatchEvent(new CustomEvent('focus', { detail: ids }))
}
/** Canvas event of revealNodes. */
export const REVEAL_EVENT = 'reveal'
/**
 * A node was just created: if it is off-screen, pan just enough to show it — keeping the zoom, so the rest of the
 * board does not fly away.
 */
export function revealNodes(ids: string[]) {
  if (ids.length) canvasEvents.dispatchEvent(new CustomEvent(REVEAL_EVENT, { detail: ids }))
}
/** Canvas event of announceWireCuts (detail: WireCutDetail). */
export const WIRES_CUT_EVENT = 'wires-cut'
export interface WireCutDetail {
  ids: string[]
  /** Where the wire was cut (screen point of the click); none = its middle. */
  at?: { x: number; y: number }
}
/**
 * These wires are about to be cut: the canvas plays the cut animation from what it still shows. Must be called
 * BEFORE the store change (the canvas reads the wires' drawn paths synchronously).
 */
export function announceWireCuts(ids: string[], at?: { x: number; y: number }) {
  if (ids.length) canvasEvents.dispatchEvent(new CustomEvent<WireCutDetail>(WIRES_CUT_EVENT, { detail: { ids, at } }))
}

// ---------------- selection helpers ----------------
export function selectedSceneIds(): string[] {
  const { selectedIds } = useUI.getState()
  const scenes = new Set(useProject.getState().project.scenes.map((s) => s.id))
  return selectedIds.filter((id) => scenes.has(id))
}

/**
 * Assets to connect: the ones selected ON THE CANVAS when there are any; otherwise the library selection.
 * Never both — a library selection made earlier is easy to forget and would silently link extra images.
 */
export function selectedAssetIds(): string[] {
  const { selectedIds, librarySelection } = useUI.getState()
  const takeIds = new Set(useRuns.getState().takes.map((t) => t.id))
  return pickAssetSelection(selectedIds, librarySelection, new Set(useProject.getState().project.assets.map((a) => a.id)), takeIds)
}

/**
 * Pure rule behind selectedAssetIds (unit-tested). The library selection is used only when the canvas selection
 * holds nothing but scenes: with a video (take) node selected the user is connecting that video, not old cards.
 */
export function pickAssetSelection(canvasSelection: string[], librarySelection: string[], assetIds: Set<string>, takeIds?: ReadonlySet<string>): string[] {
  const onCanvas = canvasSelection.filter((id) => assetIds.has(id))
  if (onCanvas.length) return [...new Set(onCanvas)]
  if (takeIds && canvasSelection.some((id) => takeIds.has(id))) return []
  return [...new Set(librarySelection.filter((id) => assetIds.has(id)))]
}

/** Take (video) nodes selected on the canvas. */
export function selectedTakeIds(): string[] {
  const { selectedIds } = useUI.getState()
  const takes = new Set(useRuns.getState().takes.map((t) => t.id))
  return selectedIds.filter((id) => takes.has(id))
}

/** "S03·T2" — short label of a take (toasts, file names). Tokens that lose their video become `videoLabel(id)`. */
export function takeLabel(takeId: string): string {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return 'video'
  const scene = useProject.getState().project.scenes.find((s) => s.id === take.sceneId)
  return takeCode(scene?.order, take.number)
}

// ---------------- connecting ----------------
/** Link assets (reference images) to scenes in one undo step and report what happened. */
export function linkAssets(sceneIds: string[], assetIds: string[]) {
  if (!sceneIds.length || !assetIds.length) return
  const res = useProject.getState().addRefs(sceneIds, assetIds)
  const names = assetIds.map((id) => useProject.getState().project.assets.find((a) => a.id === id)?.name).filter(Boolean)
  if (res.added) {
    toast(
      `Đã nối ${names.slice(0, 3).join(', ')}${names.length > 3 ? ` +${names.length - 3}` : ''} → ${res.scenes} cảnh${res.skipped ? ` (bỏ qua ${res.skipped} vì vượt giới hạn ảnh)` : ''}`,
      { tone: 'success', action: undoToastAction() },
    )
  } else if (res.skipped) {
    toast(`Không nối được: vượt giới hạn ảnh của model (${res.skipped}).`, { tone: 'warning' })
  } else {
    toast('Các cảnh đã có sẵn những tham chiếu này.', { tone: 'info' })
  }
}

/** Link takes (reference videos, @video_N) to scenes. Only completed takes can be used. */
export function linkTakes(sceneIds: string[], takeIds: string[]) {
  if (!sceneIds.length || !takeIds.length) return
  const takes = useRuns.getState().takes
  const ready = takeIds.filter((id) => takes.find((t) => t.id === id)?.status === 'completed')
  // A scene cannot reference its own takes (that would be a loop in the story).
  const ownScene = new Map(takes.map((t) => [t.id, t.sceneId]))
  if (!ready.length) {
    toast('Video chưa tạo xong nên chưa dùng làm tham chiếu được.', { tone: 'warning' })
    return
  }
  const targets = sceneIds.filter((sid) => ready.some((t) => ownScene.get(t) !== sid))
  if (!targets.length) {
    toast('Không thể dùng video của chính cảnh này làm tham chiếu cho nó.', { tone: 'warning' })
    return
  }
  // Per pair: a scene never gets one of its own takes, even when several scenes and takes are linked at once.
  const res = useProject.getState().addVideoRefs(targets, ready, (sid, t) => ownScene.get(t) === sid)
  if (res.added) {
    toast(`Đã nối ${ready.map(takeLabel).join(', ')} làm video tham chiếu → ${res.scenes} cảnh${res.skipped ? ` (bỏ qua ${res.skipped})` : ''}`, {
      tone: 'success',
      action: undoToastAction(),
    })
  } else if (res.skipped) {
    toast('Không nối được: model/chế độ của cảnh không nhận thêm video tham chiếu.', { tone: 'warning' })
  } else {
    toast('Các cảnh đã có sẵn video này.', { tone: 'info' })
  }
}

/** "C" — connect every selected asset/take to every selected scene (matrix connect). */
export function connectSelection() {
  const scenes = selectedSceneIds()
  const assets = selectedAssetIds()
  const takes = selectedTakeIds()
  if (!scenes.length || (!assets.length && !takes.length)) {
    toast('Chọn ít nhất 1 nhân vật/bối cảnh hoặc 1 video, và 1 cảnh, rồi bấm C.', { tone: 'warning' })
    return
  }
  if (assets.length) linkAssets(scenes, assets)
  if (takes.length) linkTakes(scenes, takes)
  // Cards picked in the library (not on the canvas) have been used: clear them so they are not linked again later.
  const ui = useUI.getState()
  if (assets.length && ui.librarySelection.length && !ui.selectedIds.some((id) => assets.includes(id))) ui.setLibrarySelection([])
}

/**
 * For the prompt editor: make sure `assetId` is linked to the scene and return its "@image_N" token.
 * Returns null when it cannot be linked (image limit).
 */
export function ensureAssetToken(sceneId: string, assetId: string): string | null {
  const state = useProject.getState()
  let scene = state.project.scenes.find((s) => s.id === sceneId)
  if (!scene) return null
  if (!scene.refs.includes(assetId)) {
    const res = state.addRefs([sceneId], [assetId])
    if (!res.added) {
      toast('Không nối được: vượt giới hạn ảnh của model.', { tone: 'warning' })
      return null
    }
    scene = useProject.getState().project.scenes.find((s) => s.id === sceneId)!
  }
  return tokenForAsset(useProject.getState().project, scene, assetId)
}

// ---------------- create / delete / duplicate ----------------
/**
 * New empty scene. `position` (a double-click on the canvas): there, moved down just enough not to cover a node.
 * Otherwise next to where the user works (placementHint).
 */
export function newScene(position?: XY) {
  const st = useProject.getState()
  const id = st.addScene({}, position ? { position: freeSpotFrom(st.project, position) } : { hint: placementHint() })
  useUI.getState().select([id])
  revealNodes([id])
  return id
}

/** "N" — create the next scene after the (last) selected scene, inheriting its references and settings. */
export function nextScene(position?: XY) {
  const sel = selectedSceneIds()
  const project = useProject.getState().project
  const from = sel.length ? project.scenes.filter((s) => sel.includes(s.id)).sort((a, b) => b.order - a.order)[0] : undefined
  if (!from) return newScene(position)
  const id = useProject.getState().createNextScene(from.id, position)
  useUI.getState().select([id])
  revealNodes([id])
  toast(`Đã tạo cảnh tiếp theo sau ${sceneCode(from.order)} (giữ ảnh/video tham chiếu và cấu hình).`, { tone: 'success', action: undoToastAction() })
  return id
}

/**
 * New scene that continues from a finished take: same references as the take's scene, the take as @video_1
 * and a prompt starter. Placed at `position`; else right of the take when the user dragged it out of its scene's row
 * (that is where they look at it); else below the source scene — also for a take only nudged on its slot or resized
 * in place: it is still in the row, and the card right of it would sit where the scene's next take goes.
 */
export function createSceneFromTake(takeId: string, position?: XY) {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return null
  if (take.status !== 'completed') {
    toast('Video chưa tạo xong.', { tone: 'warning' })
    return null
  }
  const project = useProject.getState().project
  const source = project.scenes.find((s) => s.id === take.sceneId)
  if (!source) {
    toast('Cảnh gốc của video này đã bị xoá.', { tone: 'warning' })
    return null
  }
  if (!usesVideoRefs(source.settings)) {
    toast('Chế độ của cảnh gốc không nhận video tham chiếu. Đổi model/chế độ (ví dụ Seedance 2.5) rồi thử lại.', { tone: 'warning' })
    return null
  }
  const leftRow = !!take.position && currentTakeRows().offRow.has(take.id)
  const at =
    position ??
    (leftRow && take.position
      ? freeSpotFrom(project, { x: take.position.x + (take.size?.w ?? LAYOUT.takeW) + LAYOUT.takeOffsetX, y: take.position.y })
      : undefined)
  const id = useProject.getState().createNextScene(source.id, at, { videoRefs: [takeId], prompt: 'Continue from @video_1: ' })
  useUI.getState().select([id])
  revealNodes([id])
  // The gateway of the next run refuses the new scene's @video_1 (canvasapp and development mode take none yet):
  // the same cap store/runs check() reads (core/runGate).
  if (refVideosProblem(1, getProvider(activeProviderId()).capabilities(source.settings.model).maxRefVideos))
    toast(`Đã tạo cảnh tiếp nối từ ${takeLabel(takeId)} (@video_1). Lưu ý: cổng canvasapp (cả chế độ Phát triển) chưa nhận video tham chiếu — bỏ video tham chiếu (@video_1) khỏi cảnh để chạy cảnh này.`, {
      tone: 'warning',
      action: undoToastAction(),
      ms: 9000,
    })
  else toast(`Đã tạo cảnh tiếp nối từ ${takeLabel(takeId)} (@video_1).`, { tone: 'success', action: undoToastAction() })
  return id
}

export function duplicateSelection() {
  const ids = selectedSceneIds()
  if (!ids.length) return
  const created = useProject.getState().duplicateScenes(ids)
  useUI.getState().select(created)
  toast(`Đã nhân bản ${created.length} cảnh.`, { tone: 'success', action: undoToastAction() })
}

export { keyboardDeletePlan, checkTakeDelete, type TakeDeleteConfirm } from './core/deletePlan'

/**
 * Delete what is selected: cut selected wires, delete scenes, hide asset nodes from the canvas (one undo step),
 * and delete selected takes for good (after confirmation when a finished video would be lost or is used as @video;
 * takes are not undoable). Takes selected together with their own scene are spared (keyboardDeletePlan): deleting
 * the scene hides them and Undo brings them back.
 */
export function deleteSelection() {
  const { selectedIds, selectedEdgeIds } = useUI.getState()
  const project = useProject.getState().project
  const takes = useRuns.getState().takes
  const sceneById = new Map(project.scenes.map((s) => [s.id, s]))
  const assetSet = new Set(project.assets.map((a) => a.id))

  const folderSet = new Set((project.folders ?? []).map((f) => f.id))
  const sceneIds = selectedIds.filter((id) => sceneById.has(id))
  const hideAssetIds = selectedIds.filter((id) => assetSet.has(id))
  const folderIds = selectedIds.filter((id) => folderSet.has(id))
  const plan = keyboardDeletePlan(selectedIds, new Set(sceneById.keys()), new Map(takes.map((t) => [t.id, t.sceneId])))
  const takeIds = plan.takes
  const deadScenes = new Set(sceneIds)

  const refs: { sceneId: string; assetId: string }[] = []
  const videoRefs: { sceneId: string; takeId: string }[] = []
  const frames: { sceneId: string; which: 'first' | 'last' }[] = []
  const folderLinks: { folderId: string; kind: FolderLinkKind; from: string }[] = []
  for (const id of selectedEdgeIds) {
    const e = parseEdgeId(id)
    if (!e) continue
    if (isFolderEdge(e.kind)) {
      // Wires into a folder node that is deleted anyway go with it.
      if (folderSet.has(e.to) && !folderIds.includes(e.to)) folderLinks.push({ folderId: e.to, kind: e.kind, from: e.from })
      continue
    }
    const scene = sceneById.get(e.to)
    // Skip wires that no longer exist or whose scene is being deleted anyway.
    if (!scene || deadScenes.has(scene.id)) continue
    if (e.kind === 'ref' && scene.refs.includes(e.from)) refs.push({ sceneId: e.to, assetId: e.from })
    else if (e.kind === 'vref' && scene.videoRefs.includes(e.from)) videoRefs.push({ sceneId: e.to, takeId: e.from })
    else if (e.kind === 'first' && scene.firstFrame === e.from) frames.push({ sceneId: e.to, which: 'first' })
    else if (e.kind === 'last' && scene.lastFrame === e.from) frames.push({ sceneId: e.to, which: 'last' })
  }

  const links = refs.length + videoRefs.length + frames.length + folderLinks.length
  // Ask BEFORE changing anything: Cancel must leave the whole selection untouched.
  if (takeIds.length) {
    const check = checkTakeDelete(takeIds, takes, project.scenes, { ignoreScenes: deadScenes, label: takeIds.length === 1 ? takeLabel(takeIds[0]) : undefined })
    if (check.question && !window.confirm(check.question)) return
  }
  // Takes first: their labels ("video S01·T1") need their scene, which deleteItems may remove.
  const projectBefore = useProject.getState().project
  // The canvas animates the wires being cut (before they vanish from the store).
  if (links) {
    announceWireCuts([
      ...refs.map((r) => edgeId('ref', r.assetId, r.sceneId)),
      ...videoRefs.map((r) => edgeId('vref', r.takeId, r.sceneId)),
      ...frames.map((f) => {
        const s = sceneById.get(f.sceneId)
        return edgeId(f.which, (f.which === 'first' ? s?.firstFrame : s?.lastFrame) ?? '', f.sceneId)
      }),
      ...folderLinks.map((l) => edgeId(l.kind, l.from, l.folderId)),
    ])
  }
  const takesDeleted = takeIds.length ? (deleteTakes(takeIds, { confirm: false, toast: false }) ?? 0) : 0
  if (sceneIds.length || hideAssetIds.length || folderIds.length || links) {
    useProject.getState().deleteItems({ sceneIds, hideAssetIds, refs, videoRefs, frames, folderIds, folderLinks }, videoLabel)
  }
  if (!sceneIds.length && !hideAssetIds.length && !folderIds.length && !links && !takesDeleted) return
  useUI.getState().clearSelection()
  const deleted = [
    sceneIds.length && `${sceneIds.length} cảnh`,
    takesDeleted && `${takesDeleted} video`,
    folderIds.length && `${folderIds.length} thư mục khỏi canvas (file đã lưu vẫn còn)`,
    links && `${links} dây nối`,
  ].filter(Boolean)
  const said = [deleted.length && `Đã xoá ${deleted.join(', ')}`, hideAssetIds.length && `${deleted.length ? 'đã ẩn' : 'Đã ẩn'} ${hideAssetIds.length} thẻ khỏi canvas`]
  const undoable = sceneIds.length || hideAssetIds.length || folderIds.length || links
  // Renumbering off: prompts that kept numbers now naming another picture / video.
  const stale = staleNoteSince(projectBefore, useProject.getState().project)
  toast(`${said.filter(Boolean).join('; ')}${stale}.${takesDeleted ? ' ' + TAKES_GONE_NOTE : ''}`, {
    ...(undoable ? { action: undoToastAction() } : {}),
    ...(stale ? { tone: 'warning' as const, ms: 8000 } : {}),
  })
}

/** Appended to every toast about deleted takes. */
export const TAKES_GONE_NOTE = '(Video đã xoá không hoàn tác được.)'

export interface DeleteTakesOptions {
  /**
   * Ask first (window.confirm). true (default) = when a finished video would be lost or a scene uses one as @video;
   * 'usedOnly' = only for @video users (the caller already confirmed, e.g. a two-click button); false = never.
   */
  confirm?: TakeDeleteConfirm
  /** Show the result toast (default true). */
  toast?: boolean
  /** Scenes deleted in the same operation: their @video uses are not mentioned in the question. */
  ignoreScenes?: ReadonlySet<string>
}

/**
 * The one way to delete takes for good (canvas node, take viewer, queue, Delete key): asks when needed, cancels
 * running jobs, removes the takes (and drops them from every scene's @video references, renumbering prompts),
 * deletes their poster/video files (nothing can bring a deleted take back, so its media would only fill the
 * browser's quota), drops them from the selection and says so in a toast.
 * Returns how many takes were deleted, or null when the user cancelled the question.
 */
export function deleteTakes(takeIds: readonly string[], opts: DeleteTakesOptions = {}): number | null {
  const project = useProject.getState().project
  const all = useRuns.getState().takes
  const check = checkTakeDelete(takeIds, all, project.scenes, {
    confirm: opts.confirm ?? true,
    ignoreScenes: opts.ignoreScenes,
    label: takeIds.length === 1 ? takeLabel(takeIds[0]) : undefined,
  })
  if (!check.ids.length) return 0
  if (check.question && !window.confirm(check.question)) return null
  // Labels before the takes are gone.
  const label = check.ids.length === 1 ? takeLabel(check.ids[0]) : `${check.ids.length} video`
  const usedCodes = check.usedBy.map((s) => sceneCode(s.order))
  const ids = new Set(check.ids)
  const dead = all.filter((t) => ids.has(t.id))
  const projectBefore = useProject.getState().project
  useRuns.getState().removeTakes(check.ids)
  for (const t of dead) {
    if (t.posterId) void deleteMedia(t.posterId).catch(() => undefined)
    if (t.videoId) void deleteMedia(t.videoId).catch(() => undefined)
  }
  const ui = useUI.getState()
  if (ui.selectedIds.some((id) => ids.has(id))) ui.select(ui.selectedIds.filter((id) => !ids.has(id)))
  const stale = staleNoteSince(projectBefore, useProject.getState().project, '@video')
  // toast: false → the caller's own toast reports it (deleteSelection compares the same before / after projects).
  if (opts.toast ?? true)
    toast(`Đã xoá ${label}${usedCodes.length ? ` và bỏ @video ở ${usedCodes.join(', ')}` : ''}${stale}. ${TAKES_GONE_NOTE}`, stale ? { tone: 'warning', ms: 8000 } : {})
  return dead.length
}

/**
 * Delete takes for good without asking and without a toast.
 * @deprecated use `deleteTakes(ids, { confirm, toast })`.
 */
export function deleteTakesForever(takeIds: string[]): number {
  return deleteTakes(takeIds, { confirm: false, toast: false }) ?? 0
}

// ---------------- assets from files ----------------
export async function createAssetsFromFiles(files: File[], opts: { kind?: AssetKind; position?: XY | null } = {}): Promise<string[]> {
  const images = files.filter((f) => /^image\//.test(f.type))
  if (!images.length) {
    toast('Chỉ nhận file ảnh (JPG, PNG, WEBP).', { tone: 'warning' })
    return []
  }
  const ids: string[] = []
  let i = 0
  for (const file of images) {
    const imageId = await putBlob(file, 'img')
    const name = file.name.replace(/\.[^.]+$/, '').replace(/[_-]+/g, ' ').trim().slice(0, 40) || 'Ảnh'
    const position = opts.position ? { x: opts.position.x + i * 24, y: opts.position.y + i * 24 } : (opts.position ?? null)
    ids.push(useProject.getState().addAsset({ name, kind: opts.kind ?? 'character', imageIds: [imageId], position }))
    i++
  }
  toast(`Đã thêm ${ids.length} mục vào thư viện.`, { tone: 'success' })
  return ids
}

export async function addImagesToAsset(assetId: string, files: File[]) {
  if (!useProject.getState().project.assets.some((a) => a.id === assetId)) return
  const ids: string[] = []
  for (const f of files.filter((f) => /^image\//.test(f.type))) ids.push(await putBlob(f, 'img'))
  if (!ids.length) return
  // Storing takes a while: append to the images the asset has NOW (the user may have removed, reordered or added
  // images meanwhile), not to the list read before the writes.
  const current = useProject.getState().project.assets.find((a) => a.id === assetId)
  if (!current) {
    for (const id of ids) void deleteMedia(id).catch(() => undefined)
    return
  }
  useProject.getState().updateAsset(assetId, { imageIds: [...current.imageIds, ...ids] })
}

// ---------------- running ----------------
/**
 * Open the run confirmation dialog (cost summary) for scenes. Defaults to the selection. Every way to start a paid
 * run goes through it (cost + wallet shown, a double click cannot queue twice). `follow`: open the new take after.
 */
export function requestRun(sceneIds: string[] = selectedSceneIds(), opts: { follow?: boolean } = {}) {
  if (!sceneIds.length) {
    toast('Chọn cảnh cần chạy trước.', { tone: 'warning' })
    return
  }
  useUI.getState().openDialog({ kind: 'runConfirm', sceneIds, follow: opts.follow })
}

/**
 * "Chạy lại" on a take. A canvasapp take whose submit outcome is unknown is re-sent as the SAME take (same key: the
 * job it may already have created is looked up first, so it is never paid twice). Anything else → the cost dialog
 * for a new take of its scene.
 */
export function rerunTake(takeId: string, opts: { follow?: boolean } = {}) {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return
  if (!isUncertainSubmit(take)) {
    requestRun([take.sceneId], opts)
    return
  }
  const dev = providerOf(take) === 'dev'
  const ok = window.confirm(
    dev
      ? `${takeLabel(takeId)}: không rõ lần gửi trước đã tới canvasapp giả lập (chế độ Phát triển) hay chưa.\n\n` +
          'SanoVids sẽ tìm job đó trên máy chủ giả lập trước và chỉ gửi lại (cùng mã yêu cầu) khi không thấy. Muốn xem trước: Bảng phát triển › Job & đơn nạp / Nhật ký.\n\nGửi lại?'
      : `${takeLabel(takeId)}: không rõ lần gửi trước đã tới canvasapp hay chưa.\n\n` +
          'SanoVids sẽ tìm job đó trên canvasapp trước và chỉ gửi lại (cùng mã yêu cầu) khi không thấy. Chắc ăn nhất: mở canvasapp.io.vn, xem phiên “SanoVids bridge” — nếu job đã có ở đó thì bấm Huỷ và tải video trên canvasapp.\n\nGửi lại?',
  )
  if (!ok) return
  const res = useRuns.getState().retry(takeId)
  if (!res) return
  if (res.error) toast(res.error, { tone: 'error' })
  else toast(`Đang gửi lại ${takeLabel(takeId)} (cùng mã yêu cầu, tìm job cũ trước).`, { tone: 'success' })
}

/**
 * "Huỷ" of a queued / running take (queue row, Xem take). When its video is already made and paid (the site's job is
 * finished, SanoVids is downloading it or waits to try again) it asks first: cancelling drops that video in SanoVids.
 * Then cancels and says what it means for the credits. Returns false when nothing was cancelled.
 */
export function cancelTake(takeId: string): boolean {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take || (take.status !== 'queued' && take.status !== 'processing')) return false
  const demoPaid = chargedDemo(take)
  const facts: CancelFacts = {
    label: takeLabel(takeId),
    provider: providerOf(take),
    status: take.status,
    cost: take.cost,
    demoPaid,
    sentAway: !demoPaid && !!take.remoteId,
    videoReady: remoteVideoReady(takeId),
  }
  const question = cancelQuestion(facts)
  if (question && !window.confirm(question)) return false
  useRuns.getState().cancel(takeId)
  const said = cancelToastText(facts)
  toast(said.text, said.warning ? { tone: 'warning', ms: 7000 } : {})
  return true
}

/** Enqueue immediately (used by the confirm dialog). */
export function runNow(sceneIds: string[]) {
  const res = useRuns.getState().enqueue(sceneIds)
  if (res.error) {
    toast(res.error, { tone: 'error' })
    return res
  }
  // Say which wallet: canvasapp (or, in development mode, its simulation) charges the account when it accepts the job.
  const kind = creditKindOf(activeProviderId())
  const cost =
    kind === 'demo'
      ? `−${formatCredits(res.cost, kind)}`
      : kind === 'dev'
        ? `≈ ${formatCredits(res.cost, kind)} (giả lập, trừ khi máy chủ giả lập nhận job)`
        : `≈ ${formatCredits(res.cost, kind)} canvasapp (trừ khi canvasapp nhận job)`
  toast(`Đã gửi ${res.queued} cảnh vào hàng đợi · ${cost}${res.skipped.length ? ` · bỏ qua ${res.skipped.length}` : ''}`, { tone: 'success' })
  return res
}

export function restoreFromTake(takeId: string) {
  const runs = useRuns.getState()
  const take = runs.takes.find((t) => t.id === takeId)
  if (!take) return
  const project = useProject.getState().project
  if (!project.scenes.some((s) => s.id === take.sceneId)) {
    toast('Cảnh của take này đã bị xoá.', { tone: 'warning' })
    return
  }
  const live = new Set(runs.takes.map((t) => t.id))
  // Tokens of references that no longer exist are renumbered / replaced, like removing a reference by hand.
  const r = restoredFromTake(take, project.assets, live, { renumber: project.settings.autoRenumber, videoLabel })
  // One store mutation = one undo step, so the toast's "Hoàn tác" reverts everything together.
  useProject.getState().restoreScene(take.sceneId, { prompt: r.prompt, refs: r.refs, videoRefs: r.videoRefs, settings: take.settings }, live)
  const extra = r.gone ? ` (bỏ ${r.gone} tham chiếu không còn tồn tại${r.renumbered ? ', đã đánh lại số @image/@video' : ''})` : ''
  const stale = r.stale ? ' Tự đánh lại số đang tắt — số @image/@video trong prompt có thể không còn đúng ảnh/video, hãy kiểm tra.' : ''
  toast(`Đã khôi phục prompt & tham chiếu của T${take.number}${extra}.${stale}`, {
    tone: stale ? 'warning' : 'success',
    action: undoToastAction(),
    ms: stale ? 9000 : undefined,
  })
}

// ---------------- copy / export ----------------
function compiledFor(sceneId: string) {
  const project = useProject.getState().project
  const scene = project.scenes.find((s) => s.id === sceneId)
  if (!scene) return null
  const takes = useRuns.getState().takes
  return { project, scene, compiled: compileScene(project, scene, { takeStatus: (id) => takes.find((t) => t.id === id)?.status }) }
}

export async function copyCompiledPrompt(sceneId: string) {
  const c = compiledFor(sceneId)
  if (!c) return
  try {
    await navigator.clipboard.writeText(c.compiled.text)
    toast(`Đã copy prompt ${sceneCode(c.scene.order)} (${c.compiled.charCount.toLocaleString('vi-VN')} ký tự).`, { tone: 'success' })
  } catch {
    toast('Trình duyệt chặn clipboard. Hãy copy thủ công trong ô xem trước.', { tone: 'error' })
  }
}

/** Zip with the reference images/videos named in token order (image_01_Elara.png, video_01_S03-T2.webm) + prompt.txt. */
export async function downloadSceneZip(sceneId: string) {
  const c = compiledFor(sceneId)
  if (!c) return
  const { project, scene, compiled } = c
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()
  zip.file('prompt.txt', compiled.text)
  for (const img of compiled.images) {
    const blob = await getBlob(img.imageId)
    if (!blob) continue
    const asset = project.assets.find((a) => a.id === img.assetId)
    const ext = blob.type.includes('png') ? 'png' : blob.type.includes('webp') ? 'webp' : blob.type.includes('svg') ? 'svg' : 'jpg'
    zip.file(`image_${String(img.n).padStart(2, '0')}_${asset?.tag ?? 'image'}.${ext}`, blob)
  }
  const takes = useRuns.getState().takes
  for (const v of compiled.videos) {
    const take = takes.find((t) => t.id === v.takeId)
    const blob = take?.videoId ? await getBlob(take.videoId) : null
    if (!blob) continue
    zip.file(`video_${String(v.n).padStart(2, '0')}_${takeLabel(v.takeId).replace('·', '-')}.webm`, blob)
  }
  const out = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(out)
  const a = document.createElement('a')
  a.href = url
  a.download = `${sceneCode(scene.order)}${scene.title ? '_' + scene.title.replace(/[<>:"/\\|?*]/g, '-') : ''}.zip`
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 10000)
}

/** Text a @video_N token becomes when its video is removed from a scene. */
export const videoLabel = (takeId: string) => (useRuns.getState().takes.some((t) => t.id === takeId) ? 'video ' + takeLabel(takeId) : 'video')

// ---------------- downloading videos ----------------
/**
 * Values of the file-name template tokens for a take (core/nameTemplate): {scene} "S03", {take} "T2", {title} the
 * scene title, {project}, {date} / {time} when the take was created, {model}.
 */
export function takeNameValues(takeId: string): NameValues | null {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return null
  const project = useProject.getState().project
  const scene = project.scenes.find((s) => s.id === take.sceneId)
  return {
    scene: scene ? sceneCode(scene.order) : 'S00',
    take: `T${take.number}`,
    title: scene?.title ?? '',
    project: project.name,
    date: nameDate(take.createdAt),
    time: nameTime(take.createdAt),
    model: MODELS[take.settings?.model]?.name ?? '',
  }
}

/**
 * Default file name of a take (without extension), from the "Cách đặt tên file" template (Settings → Nâng cao;
 * default '{scene}_{take} - {title}' → "S03_T2 - Ánh sáng trong hang", "S03_T2" when the scene has no title).
 */
export function defaultTakeFileBase(takeId: string): string {
  const values = takeNameValues(takeId)
  if (!values) return 'video'
  return renderNameTemplate(useDownloadPrefs.getState().nameTemplate, values) || `${values.scene}_${values.take}`
}

/** File name of a take's video (without extension): the name the user gave it ("Tên file"), else the default one. */
export function takeFileBase(takeId: string): string {
  const custom = useRuns.getState().takes.find((t) => t.id === takeId)?.fileName
  return custom || defaultTakeFileBase(takeId)
}

/**
 * "Tên file": rename the video of a take (every later save uses it: download, zip, auto-download, folder nodes).
 * The name is sanitized (no path, no forbidden characters, extension dropped); empty or the default name = back to
 * the default. Returns the name now used (without extension). Takes are not undoable: the toast says how to go back.
 */
export function renameTake(takeId: string, raw: string): string | null {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take) return null
  const clean = cleanTakeFileName(raw)
  const next = clean && clean !== defaultTakeFileBase(takeId) ? clean : null
  if ((take.fileName ?? null) !== next) {
    useRuns.getState().setTakeFileName(takeId, next)
    toast(next ? `${takeLabel(takeId)}: tên file mới “${next}”.` : `${takeLabel(takeId)}: dùng lại tên file mặc định.`, { tone: 'success' })
  }
  return takeFileBase(takeId)
}

/** One-click download of a finished take: the video (+ a .txt with the prompt that was sent). */
export async function downloadTake(takeId: string, opts: { auto?: boolean } = {}) {
  const take = useRuns.getState().takes.find((t) => t.id === takeId)
  if (!take || take.status !== 'completed') {
    if (!opts.auto) toast('Video chưa tạo xong.', { tone: 'warning' })
    return false
  }
  const files = await takeFiles(take, takeFileBase(takeId), useDownloadPrefs.getState().withPrompt)
  if (!files.length) {
    if (!opts.auto) toast('Không tìm thấy file video của take này.', { tone: 'error' })
    return false
  }
  // "Hỏi nơi lưu & tên file": a click asks where (a background auto-download never does).
  if (!opts.auto && useDownloadPrefs.getState().askWhere) {
    try {
      const res = await saveFilesAs(files, { title: `Lưu video ${takeLabel(takeId)}` })
      reportSavedAs(res, `${takeLabel(takeId)}${files.length > 1 ? ' + prompt' : ''}`)
      return res.to !== 'canceled'
    } catch (e) {
      toast(`Không lưu được video: ${(e as Error).message}`, { tone: 'error' })
      return false
    }
  }
  try {
    const res = await saveFiles(files, !opts.auto)
    reportSaved(res, `${takeLabel(takeId)}${files.length > 1 ? ' + prompt' : ''}`, files[0].name)
    return res.to !== 'pending'
  } catch (e) {
    toast(`Không lưu được video: ${(e as Error).message}`, { tone: 'error' })
    return false
  }
}

/** Toast for a finished save: where the files went, and what to do when the chosen folder could not be used. */
function reportSaved(res: SaveResult, what: string, firstName: string) {
  const renamed = res.to === 'folder' && res.names[0] && res.names[0] !== firstName ? ` (tên “${res.names[0]}” vì đã có file trùng tên)` : ''
  const extra = res.alsoSaved ? ` và ${res.alsoSaved} file đang chờ` : ''
  if (res.to === 'folder') toast(`Đã lưu ${what}${extra} vào thư mục “${res.folder}”${renamed}.`, { tone: 'success' })
  else if (res.to === 'pending')
    toast(`${what} đang chờ lưu vào “${res.folder}”: trình duyệt cần bạn cho phép ghi vào thư mục này lần nữa.`, {
      tone: 'warning',
      ms: 20000,
      action: { label: 'Cho phép & lưu', run: () => void savePendingNow() },
    })
  else if (res.reason === 'missing-folder')
    toast(`Không tìm thấy thư mục “${res.folder}” (đã đổi tên hoặc xoá?) nên đã tải ${what} về thư mục Downloads. Chọn lại thư mục trong Cài đặt.`, {
      tone: 'warning',
      ms: 8000,
    })
  else if (res.reason === 'no-permission')
    toast(`Chưa có quyền ghi vào “${res.folder}” nên đã tải ${what} về thư mục Downloads.`, { tone: 'warning', ms: 8000 })
  else toast(`Đã tải ${what} về máy.`, { tone: 'success' })
}

/** Toast for a "save as" (askWhere): where it went, or why the browser downloaded it instead. Nothing on cancel. */
function reportSavedAs(res: SaveAsResult, what: string) {
  if (res.to === 'canceled') return
  if (res.to === 'chosen') {
    const where = res.path ? ` → ${res.path}` : ` → “${res.names[0]}”`
    const extra = res.names.length > 1 ? ` (kèm “${res.names.slice(1).join('”, “')}”${res.path ? ' cùng chỗ' : ' trong Tải xuống'})` : ''
    toast(`Đã lưu ${what}${where}${extra}.`, { tone: 'success', ms: 6000 })
    return
  }
  toast(
    `Trình duyệt này không cho chọn nơi lưu nên đã tải ${what} về thư mục Tải xuống (Downloads). Dùng Chrome / Edge hoặc app SanoVids desktop để chọn nơi lưu và đặt tên.`,
    { tone: 'info', ms: 9000 },
  )
}

/** Toast button (a click, so the browser may ask for the folder permission): save the auto-downloads that wait. */
async function savePendingNow() {
  try {
    const res = await savePendingDownloads()
    if (!res) return
    if (res.to === 'folder') toast(`Đã lưu ${res.names.length} file vào thư mục “${res.folder}”.`, { tone: 'success' })
    else toast(`Chưa được phép ghi vào thư mục nên đã tải ${res.names.length} file về Downloads.`, { tone: 'warning' })
  } catch (e) {
    toast(`Không lưu được: ${(e as Error).message}`, { tone: 'error' })
  }
}

/** The chosen take of every scene (starred, else the latest completed), in scene order. */
export function chosenTakeIds(): string[] {
  const takes = useRuns.getState().takes
  const scenes = [...useProject.getState().project.scenes].sort((a, b) => a.order - b.order)
  const out: string[] = []
  for (const s of scenes) {
    const own = takes.filter((t) => t.sceneId === s.id && t.status === 'completed')
    const pick = own.find((t) => t.starred) ?? own.sort((a, b) => b.number - a.number)[0]
    if (pick) out.push(pick.id)
  }
  return out
}

/** Zip of the chosen take of every scene (S01_T2 - title.webm …) + prompts.txt (pref zipPrompts). */
export async function downloadChosenTakesZip() {
  const ids = chosenTakeIds()
  if (!ids.length) {
    toast('Chưa có video nào tạo xong.', { tone: 'warning' })
    return
  }
  const name = `${useProject.getState().project.name.replace(/[<>:"/\\|?*]/g, '-')} - video chọn.zip`
  const askWhere = useDownloadPrefs.getState().askWhere
  // Ask now, while the click still counts as a user gesture (zipping takes a while): where to save the .zip, or
  // the permission for the chosen download folder.
  const plan = askWhere ? await prepareSaveAs(name, { title: 'Lưu file .zip' }) : null
  if (plan === 'canceled') return
  if (!askWhere) await prepareFolderAccess()
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()
  const prompts: string[] = []
  // Two takes renamed alike must not overwrite each other inside the zip.
  const used = new Set<string>(['prompts.txt'])
  for (const id of ids) {
    const take = useRuns.getState().takes.find((t) => t.id === id)!
    const base = takeFileBase(id)
    for (const f of await takeFiles(take, base, false)) zip.file(uniqueInSet(f.name, used), f.data)
    prompts.push(`=== ${base} ===\n${take.promptSnapshot}`)
  }
  // "Kèm prompts.txt trong file .zip" (Settings → Nâng cao).
  if (useDownloadPrefs.getState().zipPrompts) zip.file('prompts.txt', prompts.join('\n\n'))
  const blob = await zip.generateAsync({ type: 'blob' })
  const file: FileToSave = { name, data: blob }
  try {
    if (plan) {
      reportSavedAs(await runSaveAs(plan, [file]), `${ids.length} video (.zip)`)
      return
    }
    const res = await saveFiles([file], true)
    reportSaved(res, `${ids.length} video (.zip)`, name)
  } catch (e) {
    toast(`Không lưu được file .zip: ${(e as Error).message}`, { tone: 'error' })
  }
}

/** Open the full-screen image viewer (whole picture, real aspect ratio). */
export function viewImages(imageIds: string[], index = 0, title?: string) {
  const ids = imageIds.filter(Boolean)
  if (!ids.length) return
  useUI.getState().openDialog({ kind: 'image', imageIds: ids, index, title })
}

/** Viewer for all images of a library asset. */
export function viewAssetImages(assetId: string, index = 0) {
  const asset = useProject.getState().project.assets.find((a) => a.id === assetId)
  if (asset) viewImages(asset.imageIds, index, asset.name)
}

// ---------------- canvasapp top-up (docs/SPEC-v2.md §10) ----------------
/**
 * Open the "Nạp credit canvasapp" sheet on a tab ('topup' = buy credits with SePay QR, 'history' = credit history).
 * The sheet explains by itself when top-up cannot be used here (web build, not logged in, topup_enabled false…).
 * Meant to be opened from the real-credit pill and Settings › Cổng canvasapp (wired by those components).
 */
export function openTopUp(tab: TopUpTab = 'topup') {
  useUI.getState().openDialog({ kind: 'topup', tab })
}

/**
 * Open "Bảng phát triển" (development mode: the simulated canvasapp's state, faults, request log, jobs and top-up
 * orders — components/dev/DevPanel). From the top bar bug button, Settings and the queue drawer.
 */
export function openDevPanel(tab?: DevPanelTab) {
  useUI.getState().openDialog({ kind: 'dev', tab })
}

export { undo, redo }

// Folder nodes ("Thư mục"): their commands live in ./folderActions (it also auto-saves finished takes into folders).
import './folderActions'
